### ISSUE TITLE
No ./configure in github - need to run autoconf?

### ISSUE THREAD

**Issue by tseemann** [nickjcroucher/gubbins#130]
The INSTALL says to run `./configure` but there is no script. There was no `autogen.sh` either, so I ran `autoconf` and it did create the `configure` script with a few warnings (Ubuntu 12 server):

```
% autoconf
configure.ac:3: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:10: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:21: error: possibly undefined macro: AM_PATH_PYTHON
configure.ac:23: error: possibly undefined macro: AC_MSG_WARN
```

**Comment by AidanDelaney** [comment]
Yes.  You should run "autoreconf -i".  The source is distributed in maintainer mode, rather than developer mode.  We probably should have an autogen.sh or, at least, fix the documentation.

**Comment by tseemann** [comment]
Thanks @AidanDelaney . Not sure I'll ever fully understand autotools!

**Comment by martinghunt** [comment]
Just an extra comment on this using Ubuntu, in case others run into the same problem. The second error above:

```
configure.ac:10: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

means that libtool needs to be installed:

```
apt-get install libtool
```

**Comment by summerban** [comment]
sorry,this method doesn't work for me ,i had tried all the method above

**Comment by andrewjpage** [comment]
Which of the supported installation methods did you use?
https://github.com/sanger-pathogens/gubbins/blob/master/INSTALL.md

**Comment by shardator** [comment]
Please fix this, and put configure in the source tree. Impossible to run autoconf w/o errors.

**Comment by NaughtyCatRun** [comment]
@AidanDelaney  Thanks, It works for me. But first, it throw the error below:
configure.ac:119: error: Autoconf version 2.64 or higher is required

So, I upgrade _autoconfig_ to _2.69,_ then everything is OK

**Comment by DuGu9Nue** [comment]
someone can help me...
configure.ac:178: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

**Comment by nickjcroucher** [comment]
This problem suggests you need to install pkg-config, based on https://github.com/DanBloomberg/leptonica/issues/334.

**Comment by chegJH** [comment]
For someone ends here by googling
```configure.ac:25: error: possibly undefined macro: AC_SUBST
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```
Try this first `apt install pkg-config m4 libtool automake autoconf`
