### ISSUE TITLE
FastTree doesn't honour --num_threads due to OpenMP vars

### ISSUE THREAD

**Issue by tseemann** [nickjcroucher/gubbins#155]
FastTree uses OpenMP and respects the `$OMP_NUM_THREADS` variable.

Can you override that variable if the user specifies `--num_threads` ?

It should still respect the overall `$OMP_THREAD_LIMIT` variable.

**Comment by douglasgscofield** [comment]
I would add that if the build command at http://www.microbesonline.org/fasttree/#Install is followed, the MP-enabled FastTree executable is FastTreeMP, and the non-MP executable is FastTree.  Those are the names I have given the executables in our site module.

**Comment by tseemann** [comment]
To control this in Nullarbor I just run it as `env OMP_NUM_THREADS=$threads FastTree ...`

**Comment by nickjcroucher** [comment]
Gubbins should now use the MP-enabled version by default in bf3bd21.
