### ISSUE TITLE
error while loading shared libraries: libgubbins.so.0

### ISSUE THREAD

**Issue by christianparobek** [nickjcroucher/gubbins#156]
I was able to install `gubbins` on my Ubuntu 14.04 machine yesterday using the manual install. Tried the `linuxbrew` option but ran into some problems. Anyway, I am able to execute the `python` script:

```
christian@juliano:~/Desktop$ run_gubbins.py
usage: run_gubbins.py [-h] [--outgroup OUTGROUP]
                      [--starting_tree STARTING_TREE] [--use_time_stamp]
                      [--verbose] [--no_cleanup] [--tree_builder TREE_BUILDER]
                      [--iterations ITERATIONS] [--min_snps MIN_SNPS]
                      [--filter_percentage FILTER_PERCENTAGE]
                      [--prefix PREFIX] [--threads THREADS]
                      [--converge_method CONVERGE_METHOD] [--version]
                      [--min_window_size MIN_WINDOW_SIZE]
                      [--max_window_size MAX_WINDOW_SIZE]
                      alignment_filename
run_gubbins.py: error: the following arguments are required: alignment_filename
```

However, when I try running the sample data provided on the website I run into this problem:

```
christian@juliano:~/Desktop$ run_gubbins.py ST239.aln 
Trying PTHREADS version of raxml because no single threaded version of raxml could be found. Just to warn you, this requires 2 threads.

Using FastML 3 with GTR model

gubbins: error while loading shared libraries: libgubbins.so.0: cannot open shared object file: No such file or directory
Gubbins crashed, please ensure you have enough free memory
```

I found that `src/libgubbins.la` references this missing `libgubbins.so.0` shared library, and I added this `src/` directory to my `LD_LIBRARY_PATH` variable, as this [post](https://www.gnu.org/software/gsl/manual/html_node/Shared-Libraries.html) suggests, but still runs into the same problem. I'm quite a bit out of my depth, so any help would be much appreciated.

**Comment by christianparobek** [comment]
UPDATE:
We had to update the LD_LIBRARY_PATH _in the_ `.bashrc` _file_ to include `/usr/local/lib/` (i.e. not just in the current session, since apparently `python` recalls `.bashrc`), and now it looks like it works.

**Comment by heidikira** [comment]
Hi,

I have the same error, but apparently it is no long possible to set LD_LIBRARY_PATH in the .bashrc file in Ubuntu (since version 9, see here: https://help.ubuntu.com/community/EnvironmentVariables#File-location_related_variables ))

I have nonetheless set LD_LIBRARY_PATH path  in both my current session, and also in my .bashrc file anyways, but I still get the same error.

I tried to set it up with ldconfig,and I can find that it includes the gubbins library:

```
/usr/local/lib:
    libgubbins.so.0 -> libgubbins.so.0.0.1
```

I thought that would be a work around, but it still doesn't work.  Am I doing something wrong, or is there a possible work around to having LD_LIBRARY_PATH in the .bashrc?

Help would be much appreciated ^_^

**Comment by andrewjpage** [comment]
Hi,
Gubbins has been packaged by the Debian Med team so it might be possible for you to install it with:

```
sudo apt-get install gubbins
```

**Comment by heidikira** [comment]
I am unfortunately using version 14, and its only available using apt-get from version 16.  I realize now that @christianparobek was using Ubuntu version 14, so there must be something wrong with my set-up...

**Comment by ramadatta** [comment]
> Hi,
> Gubbins has been packaged by the Debian Med team so it might be possible for you to install it with:
> 
> ```
> sudo apt-get install gubbins
> ```

Installing from the source did not work and threw the same error. 
Also to mention, I updated the LD_LIBRARY_PATH in the .bashrc file to include /usr/local/lib/, but with no success.
But,`sudo apt-get install gubbins` works for me. 

Thanks
