### ISSUE TITLE
numpy issues

### ISSUE THREAD

**Issue by danknight** [nickjcroucher/gubbins#159]
Hi,

Please can you help regarding an installation issue. I have tried to troubleshoot this but having no luck. On my linux system, brew install python works fine but when i run brew install gubbins it os not picking up numpy which is definitely installed (see below).

dk@TCD50[dk] brew install gubbins                                                    [ 9:43PM]
==> Installing gubbins from homebrew/homebrew-science
==> Using a fortran compiler found at /usr/bin/gfortran.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/sanger-pathogens/gubbins/archive/v1.4.1.tar.gz
Already downloaded: /home/dk/.cache/Homebrew/gubbins-1.4.1.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz
Already downloaded: /home/dk/.cache/Homebrew/gubbins--nose-1.3.7.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/home/dk/.linuxbrew/Cellar/g
==> Downloading https://pypi.python.org/packages/source/b/biopython/biopython-1.65.tar.gz
Already downloaded: /home/dk/.cache/Homebrew/gubbins--biopython-1.65.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/home/dk/.linuxbrew/Cellar/g
Last 15 lines from /home/dk/.cache/Homebrew/Logs/gubbins/02.python3:
--prefix=/home/dk/.linuxbrew/Cellar/gubbins/1.4.1_1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install

Numerical Python (NumPy) is not installed.

This package is required for many Biopython features.  Please install
it before you install Biopython. You can install Biopython anyway, but
anything dependent on NumPy will not work. If you do this, and later
install NumPy, you should then re-install Biopython.

You can find NumPy at http://www.numpy.org

I have tried the following solution from issue 1975, but it still doesn't work
mkdir -p /home/xxx/.local/lib/python3.5/site-packages
echo 'import site; site.addsitedir("/home/xxx/.linuxbrew/lib/python3.5/site-packages")' >> /home/xxx/.local/lib/python3.5/site-packages/homebrew.pth

Thanks
Dan

**Comment by andrewjpage** [comment]
Hi Dan,
Could you try removing numpy and reinstalling it like:
brew uninstall numpy
brew install homebrew/python/numpy --with-python3
brew install gubbins

Andrew

**Comment by danknight** [comment]
Hi Andrew,

Still no luck with installing gubbins. The ongoing numpy issue means i have to turn to ClonalFrameML or BRatNextGen. I was really hoping to use Gubbins.
Dan

**Comment by tseemann** [comment]
I also haven't been able to install `gubbins` in recent times from Brew.

This works:

```
brew reinstall homebrew/python/numpy --with-python3
```

And I also have it installed via pip

```
numpy in /bio/linuxbrew/lib/python3.4/site-packages
```

But this doesn't:

```
brew install gubbins
==> Installing gubbins from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/sanger-pathogens/gubbins/archive/v1.4.5.tar.gz
Already downloaded: /home/tseemann/.cache/Homebrew/gubbins-1.4.5.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz
Already downloaded: /home/tseemann/.cache/Homebrew/gubbins--nose-1.3.7.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/bio/linuxbrew/Cellar/gubbins/1.4.5_1/libexec/vendo
==> Downloading https://pypi.python.org/packages/source/b/biopython/biopython-1.66.tar.gz
Already downloaded: /home/tseemann/.cache/Homebrew/gubbins--biopython-1.66.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/bio/linuxbrew/Cellar/gubbins/1.4.5_1/libexec/vendo
Last 15 lines from /home/tseemann/.cache/Homebrew/Logs/gubbins/02.python3:
--prefix=/bio/linuxbrew/Cellar/gubbins/1.4.5_1/libexec/vendor
--single-version-externally-managed
--record=installed.txt

running install

Numerical Python (NumPy) is not installed.

This package is required for many Biopython features.  Please install
it before you install Biopython. You can install Biopython anyway, but
anything dependent on NumPy will not work. If you do this, and later
install NumPy, you should then re-install Biopython.

You can find NumPy at http://www.numpy.org
```

**Comment by andrewjpage** [comment]
Hi Folks,
Sorry for the delay in fixing this. I've put in a pull request on homebrew. The PYTHONPATH is set somewhere to include python2.7 packages, but not the python 3 packages, so the wrong version of numpy was picked up, and it falls over. I've modified the PYTHONPATH so that it picks up the correct numpy. The error comes from somewhere else in homebrew, but I dont know where.
Andrew

**Comment by tseemann** [comment]
It worked! Thanks @andrewjpage !

**Comment by danknight** [comment]
Thanks guys, worked a treat.

**Comment by ksw9** [comment]
Hi, I have tried to follow Andrew's above recommendation:
brew uninstall numpy
brew install homebrew/python/numpy --with-python3
brew install gubbins

However, I continue to get the following error message.  Is there something I am doing wrong?  Thank you!

Numerical Python (NumPy) is not installed.

This package is required for many Biopython features.  Please install
it before you install Biopython. You can install Biopython anyway, but
anything dependent on NumPy will not work. If you do this, and later
install NumPy, you should then re-install Biopython.

You can find NumPy at http://www.numpy.org

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues

These open issues may also help:
gubbins - Failed to import the site module (since python 3.4 -> 3.5) https://github.com/Homebrew/homebrew-science/issues/3490

**Comment by tseemann** [comment]
@ksw9 - Yes we are having the same problem.

**Comment by ksw9** [comment]
Following up on this: Is there a workaround if brewer does not work for the install?  Can I clone from Github?
Thank you!

**Comment by weixindec** [comment]
Hi, 

Just wanted to follow up on this issue. I have been trying to install Gubbins on both our linux machine with no avail. Would really appreciate any help, at all. Here's the error messages:

==> Reinstalling homebrew/science/gubbins
==> Installing dependencies for homebrew/science/gubbins: homebrew/python/numpy, libpng, freetype, libtiff, littl
==> Installing homebrew/science/gubbins dependency: homebrew/python/numpy
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://files.pythonhosted.org/packages/e0/4c/515d7c4ac424ff38cc919f7099bf293dd064ba9a600e1e3835b3edefdb
Already downloaded: /home/ttsh/.cache/Homebrew/numpy-1.11.1.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz
Already downloaded: /home/ttsh/.cache/Homebrew/numpy--nose-1.3.7.tar.gz
==> python3 -c import setuptools... --no-user-cfg install --prefix=/home/ttsh/.linuxbrew/Cellar/numpy/1.11.1/libexec/nos
==> python3 setup.py build --fcompiler=gnu95 --parallel=12 install --prefix=/home/ttsh/.linuxbrew/Cellar/numpy/1.11.1 --
==> python3 -c import numpy; assert numpy.test().wasSuccessful()
Last 15 lines from /home/ttsh/.cache/Homebrew/Logs/numpy/03.python3:

---

Ran 6161 tests in 58.064s

FAILED (KNOWNFAIL=7, SKIP=12, errors=1)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError
Running unit tests for numpy
NumPy version 1.11.1
NumPy relaxed strides checking option: False
NumPy is installed in /home/ttsh/.linuxbrew/Cellar/numpy/1.11.1/lib/python3.5/site-packages/numpy
Python version 3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.7

READ THIS: https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-python/issues
