### ISSUE TITLE
slow fastml

### ISSUE THREAD

**Issue by aldertzomer** [nickjcroucher/gubbins#167]
Hi,
Gubbins used to be pretty fast (v1.4.5 I believe) but for an unknown reason it stopped working (it was installed on biolinux 8 using apt-get) so I updated to the latest version using homebrew, but now it's about 10x slower, I'm guessing this is caused by the rather slow fastml3. How can I revert back to the older version or are there compelling reasons not to do so?
Aldert

**Comment by aldertzomer** [comment]
Recompiled from source and now it uses fastml2 (and runs as normal). I'll post the difference in runtime (and results) once it is completed if needed.

**Comment by andrewjpage** [comment]
We are working on a fix for this, but it will be a week or two before its available.

**Comment by aldertzomer** [comment]
No problem, I convinced my installation of gubbins to use fastml2.

**Comment by andrewjpage** [comment]
FastML has been removed from version 2 of Gubbins, which should correct the problem once and for all.
https://github.com/sanger-pathogens/gubbins/tree/v2.0.0
