### ISSUE TITLE
Source install doesn't install python wrappers

### ISSUE THREAD

**Issue by antunderwood** [nickjcroucher/gubbins#173]
After make install I only have

```
bin:
total 12
-rwxr-xr-x 1 anthony ngs_users 11227 Jul 22 10:44 gubbins

lib:
total 188
-rw-r--r-- 1 anthony ngs_users 108818 Jul 22 10:44 libgubbins.a
-rwxr-xr-x 1 anthony ngs_users    969 Jul 22 10:44 libgubbins.la
lrwxrwxrwx 1 anthony ngs_users     19 Jul 22 10:44 libgubbins.so -> libgubbins.so.0.0.1
lrwxrwxrwx 1 anthony ngs_users     19 Jul 22 10:44 libgubbins.so.0 -> libgubbins.so.0.0.1
-rwxr-xr-x 1 anthony ngs_users  77633 Jul 22 10:44 libgubbins.so.0.0.1
```

**Comment by andrewjpage** [comment]
Sorry theres a step missing from for installing from source:
cd python

sudo python3 setup.py install

https://github.com/sanger-pathogens/gubbins/blob/master/INSTALL.md

**Comment by antunderwood** [comment]
Thanks. What should the install path be?  - I'm using  non standard install location for gubbins

**Comment by andrewjpage** [comment]
You should be able to provide your own path like this:

python3 setup.py install --prefix=/path/to/install/directory

**Comment by antunderwood** [comment]
Thanks this worked

python setup.py install --prefix=/phengs/hpc_software/gubbins/2.0.0

**Comment by josemunozc** [comment]
I think this hasn't been added into the installation from source instructions yet. At the moment they are:

> autoreconf -i
./configure [--prefix=$PREFIX]
make
[sudo] make install
cd python
[sudo] python3 setup.py install
