### ISSUE TITLE
Can't find RAxML in path

### ISSUE THREAD

**Issue by antunderwood** [nickjcroucher/gubbins#174]
I have RAxML in path

```
type raxmlHPC
raxmlHPC is hashed (/phengs/hpc_software/RAxML/8.2.8/multithread/raxmlHPC)
```

However gubbins reports

```
No usable version of RAxML could be found, please ensure one of these executables is in your PATH:
raxmlHPC-PTHREADS-AVX
raxmlHPC-PTHREADS-SSE3
raxmlHPC-PTHREADS
 raxmlHPC-AVX
raxmlHPC-SSE3
raxmlHPC
```

**Comment by andrewjpage** [comment]
I'm guessing you've compiled RAxML and renamed the multithreaded version to be raxmlHPC?  The multithreaded version of raxml requires 2 or more threads (passing in 1 thread causes it to exit with an error).  The single threaded version doesnt let you pass in the threads parameter (-T), exiting with an error if you do. So I guess from the name of the executable which version your running.  The best solution is if you keep the default names that come out of raxml or provide a symlink to them in your PATH. In your case you would need to call it something like raxmlHPC-PTHREADS-AVX, raxmlHPC-PTHREADS-SSE3, or raxmlHPC-PTHREADS depending on your setup (I'm guessing AVX).

**Comment by antunderwood** [comment]
I've sym linked raxmlHPC-PTHREADS to point to the raxmlHPC executable and all is well :)

And it works with Python 2.7!
