### ISSUE TITLE
Linuxbrew installs 1.4.7 still

### ISSUE THREAD

**Issue by flashton2003** [nickjcroucher/gubbins#176]
I just installed via linuxbrew and got v1.4.7 rather than v2.

**Comment by andrewjpage** [comment]
Hi,
Theres a pull request in with homebrew to update the version, so I have to
wait for them to merge the new recipe.
Andrew

**Comment by flashton2003** [comment]
awesome, thank you!

**Comment by andrewjpage** [comment]
Updated now.
