### ISSUE TITLE
Ns generated in filtered .phylip file

### ISSUE THREAD

**Issue by cam09** [nickjcroucher/gubbins#178]
Hi,

Is there a reason behind the filtered_polymorphic_sites.phylip file containing 'N' bases in some of the sequences? The input file does not contain any, so I'm unsure why N's are generated.

Thanks,
Cam

**Comment by andrewjpage** [comment]
The recombination regions are masked out with Ns.

**Comment by bforde** [comment]
Hi Andrew can you clarify please. In my alignment files the number of Ns
does not correlate to the number of SNPs identified in recombinant regions.
Also Ns in the alignment file are skewing the topology of the final tree
and introducing branches where there should be none.

Cheers

Brian

**Comment by andrewjpage** [comment]
Hi Brian,
The whole recombination region gets masked out with Ns, not just the SNPs. You mentioned that there are branches where you expect there to be none? Is the scale the same between your original tree and the output of gubbins (so were the branches always there but just compressed due to recombination)?
Unfortunately without looking at the data I cant really give you an answer.
Regards,
Andrew

**Comment by bforde** [comment]
Hi Andrew,

Thanks for getting back. It is actually the opposite that we are seeing i.e
there are not enough masked regions in the filtered alignment file.

With regards to the branch it might best be explained with an example.

Based on the filtered alignment file StrainB has diverged directly from
strainA. However, in the tree we see strainA and B diverging from a common
ancestor. I can only concluded that Ns in the sequence of strainB are
introducing some uncertainty.

I am happy to send you the data if it would help

Brian

**Comment by areejalsheikh** [comment]
Hi Andrew,

I have a similar question to Brian's. I found the N's in my phy file, which now I understand are masked recombinant regions. But what I don't understand is why do some strains have those N's but not others. If these are core SNPs, shouldn’t recombinant SNPs be masked in all strains?

E.g.
ACGGGACAGGGAGGTCTCACAATGCAA
ANNNNNNNNNNNNNNNNNNNNNNNNNA
ACGGGACAGGGAGGTCTCACAATGCAA

My concern is that the number of SNPs (shown at the header of phy file) is larger than that expected by 1000, which I think is accounting for those N's. 

Thanks for your help.
Areej

**Comment by areejalsheikh** [comment]
Hi Andrew,

I have a similar question to Brian's. I found the N's in my phy file, which now I understand are masked recombinant regions. But what I don't understand is why do some strains have those N's but not others. If these are core SNPs, shouldn’t recombinant SNPs be masked in all strains?

E.g.

```
ACGGGACAGGGAGGTCTCACAATGCAA
ANNNNNNNNNNNNNNNNNNNNNNNNNA
ACGGGACAGGGAGGTCTCACAATGCAA
```

My concern is that the number of SNPs (shown at the header of phy file) is larger than that expected by 1000, which I think is accounting for those N's. 

Thanks for your help.
