### ISSUE TITLE
Inconsistencies in branch stats file

### ISSUE THREAD

**Issue by kelwyres** [nickjcroucher/gubbins#181]
Hi, 
I'm running Gubbins 2.0.0 and seeing some inconsistencies in my branch stats output files, including outputs for distinct analyses using different sets of sequences. For example...

Node	Total_SNPs	Num_of_SNPs_inside_recombinations	Num_of_SNPs_outside_recombinations	Num_of_Recombination_Blocks	Bases_in_Recombinations	r/m	rho/theta	Genome_Length	Bases_in_Clonal_Frame
573.1446	98	0	98	0	79847	0.000000	0.000000	5343462	5263613

So there are 0 recombination blocks on the branch leading to node 573.1446 but somehow there are 79847 bases in recombinant regions? Is the number of bases in recombinant regions counting everything in the history of that node rather than just the preceding branch? 

Thanks in advance for your clarification of this,
Kelly

**Comment by ammaraziz** [comment]
What are the stats for the other nodes? Most likely you are seeing a recombination block identified in the internal nodes which are carried over.

**Comment by flashton2003** [comment]
I was also wondering about the 0 recombination blocks, >0 bases in recombinations so thanks for clarification.

So, if I want to know the overall r/m for a strain, I have to figure out all the parent nodes for that strain back to the root and sum the total SNPs and num snps inside recombinations?

I guess the node labelled tree will be helpful for that.

**Comment by andrewjpage** [comment]
The node labelled tree has been added back in as an output. And yes the counts are cumulative from the root of the tree.
