### ISSUE TITLE
Number of SNPs is more than input alignment

### ISSUE THREAD

**Issue by areejalsheikh** [nickjcroucher/gubbins#182]
Hi,

My issue is that the resulting phylip file has more SNPs than the input. Here is a brief of my analysis:

I have ~100 isolates of the same species. I mapped the reads onto the reference genome, and created an alignment of 'pseudogenomes', which was used as input to Gubbins. Each pseudogenome is composed of the reference genome, but with the substitution SNPs predicted for each strain integrated into it, as described in ([http://mbio.asm.org/content/7/2/e00347-16.full]). Point is, I know exactly the number of substitution SNPs provided in the input. The resulting phylip file, however, had ~1000SNPs more even after filtering recombination! Which doesn't make sense because the program predicted several recombined regions for that dataset.

Initially, I thought that the program is counting the N's in the phylip file so I removed all the columns where an N is found. The final number of SNPs was still more by ~100. 

I also ran Gubbins on 5 strains from the same dataset (using the same outgroup and the same method of pseudogenomes) and the final number of SNPs was less by ~1000 SNPs, which seems about right. 

My question is, why are there still N's in the phy file, which is an alignment of all core SNPs. If the N's are there to mask recombination, then why aren't these regions removed from the phy file (and the tree)? They are quite confusing.. Most importantly, why am I getting more SNPs? 

Thank you,
Areej

**Comment by andrewjpage** [comment]
Your query is partially answered in issue https://github.com/sanger-pathogens/gubbins/issues/192
With regards to getting more SNPs out then you put in, thats quite unexpected behaviour. How are you counting SNPs? The taxa only have regions masked out, so there should be less SNPs coming out than go in, unless you are counting an N or - as a SNP (which they arent).
