### ISSUE TITLE
gubbins would not run

### ISSUE THREAD

**Issue by aphayt** [nickjcroucher/gubbins#187]
Dear Sir

I had a copy of Gubbins installed in BioLinux8 (Ubuntu 14.04). When I tried to run the program. I got:
yue@PC-027[yue] run_gubbins.py -h                                     [ 1:03PM]
/home/yue/.linuxbrew/bin/run_gubbins.py: /home/yue/.linuxbrew/Cellar/gubbins/2.2.0/libexec/bin/run_gubbins.py: /home/yue/.linuxbrew/opt/python3/bin/python3.5: bad interpreter: No such file or directory
/home/yue/.linuxbrew/bin/run_gubbins.py: line 2: /home/yue/.linuxbrew/Cellar/gubbins/2.2.0/libexec/bin/run_gubbins.py: Success
It says success but it is not quite right as I could not run the program.

Please help,
Yue

**Comment by andrewjpage** [comment]
Hi Yue,
From the error message it looks like Python is not setup correctly on your
system.  Try reinstalling python3 or contact your local system
administrator for IT support.
Regards,
Andrew

**Comment by jb2cool** [comment]
The only thing I can see that's wrong is that LinuxBrew installed Python 3.6 where as the run_gubbins.py seems to be specifically calling Python 3.5. I have temporarily put in a symbolic link to redirect Python 3.5 to 3.6 and this seems to work but the LinuxBrew instructions seem to be broken as-is.

**Comment by aphayt** [comment]
Hi Andrew

Jason found LinuxBrew could not find Python 3.5 so he redirected to 3.6. When I tried Gubbins only I got:
yue@PC-027[CampyGubbins] /home/yue/.linuxbrew/bin/run_gubbins.py      [12:25PM]
usage: run_gubbins.py [-h] [--outgroup OUTGROUP]
                      [--starting_tree STARTING_TREE] [--use_time_stamp]
                      [--verbose] [--no_cleanup] [--tree_builder TREE_BUILDER]
                      [--iterations ITERATIONS] [--min_snps MIN_SNPS]
                      [--filter_percentage FILTER_PERCENTAGE]
                      [--prefix PREFIX] [--threads THREADS]
                      [--converge_method CONVERGE_METHOD] [--version]
                      [--min_window_size MIN_WINDOW_SIZE]
                      [--max_window_size MAX_WINDOW_SIZE]
                      [--raxml_model RAXML_MODEL]
                      [--remove_identical_sequences]
                      alignment_filename
run_gubbins.py: error: the following arguments are required: alignment_filename
If I added fasta file as well, I got:
yue@PC-027[CampyGubbins] /home/yue/.linuxbrew/bin/run_gubbins.py 20ref10isolates.fa
../src/gubbins is not in your path

I could not find /src/... in the bin folder.

Many thanks,
Yue

**Comment by raymondkiu** [comment]
Hi Andrew

I have similar problem - could not run run_gubbins.py as common cannot be imported. I installed Gubbins through homebrew on my Mac. I suspect python 3.6 might be the issue?

Raymond

**Comment by JibrinLab** [comment]
Hi,
When I tried to run gubbins, I got this : run_gubbins.py 
run_gubbins.py: command not found

But when I tried to reinstall I got this: Warning: linuxbrew/science/gubbins-2.2.0 already installed

Please help.

**Comment by jb2cool** [comment]
What does your $PATH variable look like? You you have the LinuxBrew bits in it?

**Comment by JibrinLab** [comment]
@jb2cool , sure I have LinuxBrew. I already had roary installed and it's a requirement. As for the path, do I still need to set any PATH? I am using a local Linux machine and I am the administrator.

**Comment by jb2cool** [comment]
I meant is LinuxBrew referenced in your $PATH variable.

If you just call the command run_gubbins.py then the OS needs to be able to find this script, the only way it can do this is if the script is in somewhere referenced by your $PATH variable.

You could try running the script by calling it via its absolute path, that would typically be something like;
 /home/yourusername/.linuxbrew/bin/run_gubbins.py

**Comment by JibrinLab** [comment]
I got this message after running /home//.linuxbrew/bin/run_gubbins.py
: bash: /home//.linuxbrew/bin/run_gubbins.py: No such file or directory

**Comment by jb2cool** [comment]
Sorry, I corrected my thread, after the /hom and before the .linuxbrew you need to put your username. This is where LinuxBrew is installed for me, yours may be installed elsewhere.

**Comment by JibrinLab** [comment]
Thanks. I added my username. It gave me this result:

/home/osboxes/.linuxbrew/bin/run_gubbins.py
/home/osboxes/.linuxbrew/bin/run_gubbins.py: /home/osboxes/.linuxbrew/Cellar/gubbins/2.2.0/libexec/bin/run_gubbins.py: /home/osboxes/.linuxbrew/opt/python3/bin/python3.5: bad interpreter: No such file or directory
/home/osboxes/.linuxbrew/bin/run_gubbins.py: line 2: /home/osboxes/.linuxbrew/Cellar/gubbins/2.2.0/libexec/bin/run_gubbins.py: Success

I ran run_gubbins.py, still this result: run_gubbins.py: command not found

**Comment by aphayt** [comment]
I run my Gubbins from '/usr/bin/run_gubbins'. Note there is no py extension.

**Comment by JibrinLab** [comment]
@aphayt Oh thanks. My bad. Now it works without the py extension.

Thanks to @jb2cool too.

**Comment by jb2cool** [comment]
@ojonuba, that's exactly the same issue as Yue initially had when he opened this thread. Gubbins seems to be statically looking to Python 3.5 where as I suspect your LinuxBrew has installed a different version like Python 3.6

**Comment by raymondkiu** [comment]
@ojonuba @jb2cool  does it mean the solution is to run run_gubbins without py extension?

**Comment by jb2cool** [comment]
@raymondkiu remember that your issue may be different to that of @ojonuba and @aphayt (Which seem to now be in the same place).

Since your issue seems to be importing the common module i'd first of all check that you can manually import this. Go into Python (Make sure you go into the right Python as the Mac probably has 2.7 installed by default) and try manually importing common

**Comment by JibrinLab** [comment]
@raymondkiu , try running it without the .py extension and see if it works for you. Otherwise you can post the error message here and someone will help respond. Best wishes.
