### ISSUE TITLE
Losing taxa?

### ISSUE THREAD

**Issue by mstegger** [nickjcroucher/gubbins#189]
Hi,
I have been using Gubbins for a few studies and it has worked nicely. However, in a recent study I have experienced a problem where I loose a few taxa "during" the Gubbins process. Is there somehow to obtain information as to why this occurred in the generated files?

Thank you!

**Comment by andrewjpage** [comment]
Before October 2016 Gubbins would drop taxa with 100% identical sequences. This is now turned off  by default, so I would recommend updating to the latest version.
