### ISSUE TITLE
from gubbins import common                                     ImportError: cannot import name common

### ISSUE THREAD

**Issue by inestiouiri** [nickjcroucher/gubbins#191]

**Comment by andrewjpage** [comment]
Hi,
Which installation method from https://github.com/sanger-pathogens/gubbins/blob/master/INSTALL.md did you use?

**Comment by GonzaloYebra** [comment]
Hey Andrew,
I got the same error, and I installed Gubbins using LinuxBrew. Any suggestions on what could be wrong?
Thanks a lot!
