### ISSUE TITLE
Gubbins - Ns in output alignment

### ISSUE THREAD

**Issue by mstagliamonte** [nickjcroucher/gubbins#192]
Dear Gubbins Team,

I am trying to use Gubbins to scan for recombination a SNP alignment which contains no missing data. The input alignment has 21,134 sites, the output file (my_output.filtered_polymorphic_sites.fasta) contains 20,174 sites. I initially thought that this was due to the potential recombinant sites being excluded; however I noticed that there are 'Ns' in the output alignment. What are these due to?
I  apologize in case this is a duplicated topic, as I found a similar question here: https://github.com/sanger-pathogens/gubbins/issues/182 , but there is no answer yet.

Thank you for your kind attention,
Max Tagliamonte

**Comment by andrewjpage** [comment]
If at a particular site there are SNPs somewhere in the tree and at a different point there is a recombination, the recombination will be masked out with Ns.

**Comment by mstagliamonte** [comment]
Thank you, @andrewjpage  for responding back so quickly.

I am sorry, but I am not sure I understand the answer. If I understand,  the alignment is shorter, as some sites were removed because of recombination, but some other sites undergoing recombination were masked instead? I am not sure I understand the difference between the two.

Thank you,
Max

**Comment by andrewjpage** [comment]
Taking these as input:

>sample1
AAC
>sample2
AAA
>sample3
AGG

Gubbins is run and it detects a recombinaton in sample3 at coords 2-3.
>sample1
AAC
>sample2
AAA
>sample3
ANN

This recombination then gets masked out. Because there is no longer any
variation in coordinate 2, it gets filtered out, but coords 3 have some
variation C/A so is kept giving a site with an N:
>sample1
AC
>sample2
AA
>sample3
AN

**Comment by mstagliamonte** [comment]
Thank you,
I understand now. I appreciate you taking the time to write the explanation, it was really useful.

Have a nice day,
Max

**Comment by wanyuac** [comment]
I reckon coord 1 in the example above should also be removed and only leave coord 3 in the final alignment, as coord 1 is invariant.
