### ISSUE TITLE
brew install gubbins errors - no formula for pillow

### ISSUE THREAD

**Issue by sdewell** [nickjcroucher/gubbins#194]
Hi all,

Having a few issues:
Thanks for any suggestions. Python3 installed with brew, pip3 install pillow was successful in case that matters. Using Ubuntu 14.04

$ brew install gubbins
==> Installing gubbins from homebrew/science
Error: No available formula with the name "pillow" (dependency of homebrew/science/gubbins)
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

When searching for 'pil' (brew search pillow gives no results)

$ brew search pil
bluepill                             homebrew/science/piler               pilosa
cfr-decompiler                       homebrew/science/pilercr             procyon-decompiler
closure-compiler                     homebrew/science/pilon
homebrew/science/omcompiler          pillar

If you meant "pil" specifically:
Instead of PIL, consider `pip install pillow` or `brew install Homebrew/science/pillow`.

$ brew install Homebrew/science/pillow

homebrew/science/pillow was deleted from homebrew/science in commit 052866d:
  pillow: migrate to homebrew/core

To show the formula before removal run:
  git -C "$(brew --repo homebrew/science)" show 052866d^:pillow.rb

**Comment by tseemann** [comment]
@sdewell this issue belongs at https://github.com/Homebrew/homebrew-science/issues
