### ISSUE TITLE
A few questions on better practices for SNPs alignments

### ISSUE THREAD

**Issue by mstagliamonte** [nickjcroucher/gubbins#198]
Dear Authors,

I am using Gubbins to detect recombination in my alignment; my dataset is constituted by protein coding SNPs only (protozoan genome, multichromosome)

1) Can I use the SNP alignment as input, rather than the core genome?

2) If that would cause biases in the analyses, would it be correct to build a "core genome" with only the genes presenting SNPs? Maybe separated by Ns (especially in between chromosomes)? I did not actually calle variants in non coding regions (I know the people at Sanger very familiar with  the problems related to calling variants in certain protozoan intergenic regions...)

3) Should I compare only "subclades" of my single-species tree? Or would that only be necessary in case of high intra-species diversity? -EDIT- I re-read the original article, for what I understand I should probably compare isolates in subpopulation that actually have the chance to come in contact and recombine with each other.

I hope my questions are detailed enough, please let me know if there is any more information you need.

Looking forward to hearing from you,
Max

**Comment by tseemann** [comment]
Gubbins is used to find genetic recombination between bacteria.

Do protozoa recombine?

**Comment by andrewjpage** [comment]
I'm afraid that as you are trying to use the software for something other than which it was designed we cant be of much help.

**Comment by mstagliamonte** [comment]
@andrewjpage : Thank you for your kind answer, I will search further the literature for some other methods
@tseemann : some protozoa have sexual reproduction, then become haploid again (alternate reproduction cycles) thus I was mostly worried about recombination resulting from mating.

Regards,
Max
