### ISSUE TITLE
TypeError: reroot_at_midpoint() got an unexpected keyword argument 'update_splits'

### ISSUE THREAD

**Issue by malihaaziz** [nickjcroucher/gubbins#205]
Im running into the attached error.
[slurm-2236.txt](https://github.com/sanger-pathogens/gubbins/files/1418739/slurm-2236.txt)

I dont have PAUP in my path

**Comment by andrewjpage** [comment]
Which of the installation methods did you use? https://github.com/sanger-pathogens/gubbins/blob/master/INSTALL.md
