### ISSUE TITLE
Retaining recombinant free non-polymorphic sites

### ISSUE THREAD

**Issue by ramadatta** [nickjcroucher/gubbins#208]
Is there a way in gubbins to generate a fasta file which can retain recombinantion free regions of both non-polymorphic sites and polymorphic sites from the alignment ? At present gubbins seems to only generate recombinantion free regions of polymorphic sites in fasta file. Thanks

**Comment by andrewjpage** [comment]
This is not currently one of the supported outputs. You could have to use the *.recombination_predictions.gff file to mask out your original alignment.

**Comment by MostafaYA** [comment]
@ramadatta 
As a note, I am not sure if this tool can help you (https://github.com/kwongj/maskrc-svg). It basically  masks the recombinant regions in the initial alignment file that used for Gubbins.

**Comment by ramadatta** [comment]
@MostafaYA  Thanks much! I am using this now with success.
