### ISSUE TITLE
Direct output to a directory

### ISSUE THREAD

**Issue by iferres** [nickjcroucher/gubbins#209]
Is it possible to direct the output files to a specific directory instead of generating them on the working directory? The `--prefix` option doesn't seem to have that behavior. The same question for the tmp directory.
Thanks!

**Comment by andrewjpage** [comment]
I'm afraid its currently not available but it is a sensible feature to have. We can add it to the TODO list.

**Comment by iferres** [comment]
Thanks for the fast answer!
