### ISSUE TITLE
gubbins + snippy

### ISSUE THREAD

**Issue by suzumar** [nickjcroucher/gubbins#210]
I am a bit confused about the combination snippy - gubbins you suggest. If I understand right (which I might not) Using snippy-core for alignments against a reference genome will identify snps from short reads to the reference, that are mapped and finally multiple single alignments are merged to create a core-alignment. Again, since those are short reads, and these alignment only conserve  #"universally" conserved positions, I am having a hard time seeing how recombination events will be present in that core alignment.  Am I missing something here?

**Comment by andrewjpage** [comment]
The gubbins paper might help with some of your query. One signal of
recombination which gubbins can detect is where there are lots of snps on
either side of a gap, so the absence of information is utilised.

**Comment by suzumar** [comment]
OK, so if I understand right it is the gapped alignment from snippy that you suggest to be used with gubbins.  Unfortunately since I don't get enough coverage of the reference (lots of gaps and Ns), I get an error with that alignmnent.
Thanks

**Comment by andrewjpage** [comment]
You need a closer reference genome. What species are you working on? We
might have one you can use (if theres none in GenBank).
