### ISSUE TITLE
Running example files

### ISSUE THREAD

**Issue by JuliaIs** [nickjcroucher/gubbins#211]
When I try to run the example files as described in the gubbins manual, I get the message "failed while building the tree". Might anyone know how to fix it? 
Thanks!

**Comment by andrewjpage** [comment]
Hi, Which installation method from https://github.com/sanger-pathogens/gubbins/blob/master/INSTALL.md did you use?

**Comment by JuliaIs** [comment]
Thanks for the fast answer. I installed it via Bioconda (OSX)

**Comment by andrewjpage** [comment]
Which version of OSX?

**Comment by JuliaIs** [comment]
10.8.5

**Comment by andrewjpage** [comment]
I ran the steps from scratch on my laptop which is running OS X El Capitan (10.11.6), and listed them below. I'm afraid I don't have access to any machines running your version of OSX as it hasn't been used in a number of years here, so cannot test how bioconda works on it. I suspect the age of your OSX is the problem.  Your best bet is probably to use the Docker container.


Go to https://conda.io/miniconda.html
Download https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
On the commandline run:
```
bash Miniconda3-latest-MacOSX-x86_64.sh
```
Close terminal and open a new one then run:
```
conda config --add channels r
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
conda install gubbins
```

Download ftp://ftp.sanger.ac.uk/pub/project/pathogens/gubbins/PMEN1.aln.gz
Run:
```
gunzip PMEN1.aln.gz
run_gubbins.py PMEN1.aln
```

**Comment by JuliaIs** [comment]
I tried as you described, still the output is "/bin/sh: line 1:  1336 Illegal instruction: 4  raxmlHPC-AVX2 -f d -p 1 -m GTRCAT -V -s PMEN1.aln.phylip -n PMEN1.iteration_1 > /dev/null 2>&1
Failed while building the tree." 
I will try to update the OS X to fix the problem. Thank you a lot

**Comment by andrewjpage** [comment]
The error you posted indicates that your CPU doesn't support the
optimisations used by bioconda (AVX2 is only on new CPUs) for raxml. If you
manually install raxml and use the AVX or SSE3 versions it should run fine.
Regards,
Andrew
