### ISSUE TITLE
gubbins_drawer graph

### ISSUE THREAD

**Issue by mariemh23** [nickjcroucher/gubbins#212]
Hello, 
I used gubbins drawers to visualize the output of gubbins. However, the generated graph does not specify the genes where the recombinations are found. How can I fix it? 
Thank you

**Comment by simonrharris** [comment]
Hi. I would suggest trying Phandango.net instead. Simply drag the tree and recombination blocks files onto the browser along with a gff of an annotation that is the same length as the alignment you input into Gubbins, and you can interactively look at the results. At any point press p to produce a svg of what you're looking at on screen.
