### ISSUE TITLE
snippy+ gubbins

### ISSUE THREAD

**Issue by nbawe** [nickjcroucher/gubbins#214]
I have questions when using snippy + gubbins:
1) When I use reference in snippy does it have to be reference from the same dataset or well annotated genome?
2) Snippy includes reference to alignment so should I remove it before running gubbins or just leave it in and root the tree with it?

Thanks

**Comment by tseemann** [comment]
@nbawe the reference you use should be similar to the isolates in your collection being studied. "Similar" or "close" is hard to define, but you would like to see >90% coverage of the reference and < 100,000 SNPs say, preferably less.  

The annotation is not important in terms of Gubbins and Snippy, but it will affect your downstream interpretation.

You can leave the reference in or out. But you should re-run `snippy-core --noref` in that case to generate a core.full.aln without out - don't just 'remove it'.

**Comment by tseemann** [comment]
Yes, using the reference could be a good option for the `--out_group` option.

**Comment by Jessie940409** [comment]
> 

in snippy-core, this --noref  doesn't work. it also has a reference in the alignment file. What should I do to remove the reference? Can I just remove it from core.full.aln?
