### ISSUE TITLE
Question: gubbins input?

### ISSUE THREAD

**Issue by maesaar** [nickjcroucher/gubbins#215]
I have WGA aligned using mugsy and converted to fasta in galaxy. @andrewjpage or other have you tested using mugsy WGAs for gubbinst input - is it suitable alternative to snippy or not?

Thank you in advance

**Comment by maesaar** [comment]
Mugsy was used as it does not need reference hence my question - is it suitable?

**Comment by tseemann** [comment]
@mmaesaar what format is the mugsy output in?  

Docs say *and output a file /data/output/mygenomes.maf.*  

Gubbins takes a FASTA alignment.  You'll need to convert MAF to FASTA somehow.

**Comment by maesaar** [comment]
@tseemann FASTA format I used galaxy to convert from MAF to FASTA.
