### ISSUE TITLE
Run a screening test to reject alignments that will likely crash

### ISSUE THREAD

**Issue by tseemann** [nickjcroucher/gubbins#216]
The `iqtree` tool runs a simple "composition test" on any alignment you give it, and then complains if it is *too simple*.  What you want is the negative version of this, to test an alignment is too divergent, and reject it at the outset before segfaulting later.

https://github.com/Cibiv/IQ-TREE/wiki/Frequently-Asked-Questions#what-is-the-purpose-of-composition-test

**Comment by MostafaYA** [comment]
Hi, 
@tseemann @andrewjpage , I have run iqtree on an alignment file (160 sample with 201,095  SNPs). The composition test returned with 16  strains that failed the composition chi2 test.  
Gubbins was successfully run on this aln file without any error however, this took almost a day. 

When I am dividing the sample into smaller groups based on BAPS (5 in this case) and run gubbins on each of them independently, the number of bases in recombination was greatly different from the first run. 
  
* Is gubbins suitable to run on such data (with 201,095  SNPs)?
* If it is more reliable to run gubbins after dividing the population into smaller closely related groups. How it is possible to combine the results of the groups back to have a single recombination-purged alignment file and a tree file for all?

N.B., the input alignment file was prepared via generating an alignment of "pseudosequence", in which each sample is represented by the reference sequences but updated with polymorphic sites predicted for each strain. 

Thanks and best regards,

**Comment by nickjcroucher** [comment]
> If it is more reliable to run gubbins after dividing the population into smaller closely related groups. How it is possible to combine the results of the groups back to have a single recombination-purged alignment file and a tree file for all?

This is the way to run the analysis, but there is no way of combining the trees back together that is sensible in evolutionary terms - there is just too much recombination in many populations for the deep ancestry to be represented by a single tree. I would now recommend using [PopPUNK](https://github.com/bacpop/PopPUNK) or similar to subdivide your population before running a Gubbins analysis.
