### ISSUE TITLE
Gubbins with SNP Alignment?

### ISSUE THREAD

**Issue by cizydorczyk** [nickjcroucher/gubbins#218]
Hello,

Would I be correct in assuming that running Gubbins with a SNP alignment (only polymorphic sites) is inappropriate? 

Or is it possible to correct for ascertainment bias in Gubbins?

Thank you,
Conrad Izydorczyk

**Comment by andrewjpage** [comment]
Gubbins uses the distances between SNPs when calculating the SNP densities & detecting putative recombinations. So you need the whole genome. Other algorithms like BratNextGen may work though with this type of data.

**Comment by cizydorczyk** [comment]
Alright, thanks for the clarification!
