### ISSUE TITLE
SNP counts on branches

### ISSUE THREAD

**Issue by nwheeler443** [nickjcroucher/gubbins#225]
In the final_tree.tre output file produced by Gubbins, the branch labels that should be SNP counts are decimal numbers instead which don't match the numbers in the per_branch_statistics.csv file. Could someone please correct this?

**Comment by puethe** [comment]
Hi @simonrharris ,
could you comment on this please? I'm not entirely sure myself in which unit we measure the distances between the individual nodes.

**Comment by simonrharris** [comment]
I suspect the branch lengths in the tree are just adjustments to the lengths in the likelihood tree whereas Nicole is asking for the count of reconstructed SNPs per branch, which seems sensible given the rest of the output.
