### ISSUE TITLE
Gubbins can't find dendropy

### ISSUE THREAD

**Issue by CJREID** [nickjcroucher/gubbins#231]
I am trying to run gubbins on an alignment from snippy (have tried v3, with python3.5, and v4, with python 3.6) however I keep getting an error saying "no module named 'dendropy'" when it is called from the common.py script. Everything is installed with conda, and dendropy is definitely installed in the environment and up to date.

**Comment by puethe** [comment]
Hi.
Which version of gubbins are you using? I just did a test installation on an empty linux system. Conda installed the most recent version (2.3.4). I couldn't reproduce your error, for me the program ran flawlessly.

**Comment by CJREID** [comment]
I'm also using 2.3.4. Got it to run by pip installing dendropy then adding it to my path. Still don't know why it didn't work from regular installation though.
