### ISSUE TITLE
failed while running raxml internal sequence reconstruction gubbins

### ISSUE THREAD

**Issue by samlipworth** [nickjcroucher/gubbins#233]
I get the following error, the sequences are all of decent quality, I'm running gubbins installed through conda.  What is the issue?

**Comment by tseemann** [comment]
Can you try installing the latest version manually?  
The authors have made a bunch of improvements recently:
https://github.com/sanger-pathogens/gubbins/releases/tag/v2.3.4

**Comment by lexleong** [comment]
I also keep getting the same issue with raxml internal sequence reconstruction. I have recently installed the latest version from conda. When you said manually, do you mean via "sudo-apt get" instead?

**Comment by DorothyTamYiLing** [comment]
Hi,

I was trying to install Gubbins on Amazon web service. For some reason I could not install the latest version 3.3 (or 3.2.1) .I only managed to install version 2.3.4, as suggested by the above post. However I still get the error message:

ubuntu@ip-172-31-45-187:~/gubbins-2.3.4/python/scripts$ run_gubbins.py --version
2.3.4
ubuntu@ip-172-31-45-187:~$ /home/ubuntu/gubbins-2.3.4/python/scripts/run_gubbins.py --prefix biofilm180 --starting_tree 180sample_cg.phylip.treefile 180sample_cg.fasta
Failed while running RAxML internal sequence reconstruction

Please I would like to get some help here.

Thanks,
Dorothy

**Comment by nickjcroucher** [comment]
The fix is to install the latest version. I don't know why the most recent version wouldn't install through conda, but that would be a separate issue.
