### ISSUE TITLE
Midpoint rooting problem

### ISSUE THREAD

**Issue by rmostowy** [nickjcroucher/gubbins#235]
Hi all,

I'm using Gubbins to estimate r/m for sequence clusters, and it really works smoothly and splendidly. It's just that – unlike stated on Github – it doesn't return midpoint rooted trees. I'm using version 2.3.1, and this problem is indeed acknowledged but only in versions 1.3.5 to 1.4.6. 

Attached two examples of trees returned by Gubbins. Apologies if there's a simple option I'm missing.

[example1.txt](https://github.com/sanger-pathogens/gubbins/files/2383770/example1.txt)
[example2.txt](https://github.com/sanger-pathogens/gubbins/files/2383771/example2.txt)

**Comment by tseemann** [comment]
Offending documentation here: https://github.com/sanger-pathogens/gubbins#midpoint-rerooting

"From version 1.3.5 (25/6/15) to version 1.4.6 (29/2/16) trees were not midpoint rerooted by default. This doesnt have any effect on the recombination detection, but the output trees may not look as expected. Users are advised to upgrade to the latest version."

Code here:
https://github.com/sanger-pathogens/gubbins/blob/2856b5ec97e0c92a1e45f651bb660e33264b0245/python/gubbins/common.py#L459-L484

**Comment by rmostowy** [comment]
So why am I still experiencing this problem in version 2.3.1? Is this a platform-dependent DendroPy issue?

**Comment by tseemann** [comment]
You should provide your own tree to Gubbins rather than depend on its crude/fast method ?

**Comment by rmostowy** [comment]
Torsten, I'm trying to point out a problem to the developers of Gubbins which exists in the current version (at least on my server) so that it gets fixed. I can of course circumvent this problem but that's not the point.

**Comment by tseemann** [comment]
@rmostowy understood - i am trying to get them to help too through other channels.

may i ask how you installed gubbins?
conda, brew, manual etc?
it might not be using the R modules from the place you think?

**Comment by simonrharris** [comment]
Hi Rafal. Thanks for reporting this. It's not something we've seen, but we'll take a look. However, we're currently in the process of quite a major overhaul which will result in a new version soon. Once that's complete we'll look into the rooting issue.

**Comment by rmostowy** [comment]
Hi Simon,

Thanks for the reply. I had a quick chat with Nick Croucher and he said that he and John Lees had had experienced DendroPy issues whereby you have to ask to midpoint root twice to actually work. Might be worth looking at that first once you're ready to resolve this.

Cheers,
Rafal

**Comment by aretchless** [comment]
Dear Gubbins developers. Since you're doing a major overhaul, i'll just quickly note one oddity I've seen with the tree rooting (version 2.3.1). Most of the output files have a node called "internal_ROOT" (e.g. base_reconstruction, branch_statistics). However, that node is not in the labeled tree file. I can infer where it should be based on which nodes it should be attached to, but the SNP counts from branch_statistics don't seem to match up with the branch lengths in the trees. I look forward to the new version, and will check for this issue when I use it. Thanks.

**Comment by aretchless** [comment]
I may need to retract that comment. It looks like "root" is in the tree file, it's just not displayed by iTol.
