### ISSUE TITLE
install gubbins

### ISSUE THREAD

**Issue by haruosuz** [nickjcroucher/gubbins#236]
I failed to install gubbins using Conda and Homebrew as follows. Any comments would be greatly appreciated.

### Conda
```
$conda install gubbins
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - gubbins
  - subprocess32
Use "conda info <package>" to see the dependencies for each package.
```

### Homebrew
```
$brew install gubbins
Error: No available formula with the name "gubbins" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

### Environment
```
$uname -a
Darwin haruonoMacBook.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

### References
- https://github.com/sanger-pathogens/gubbins/blob/master/INSTALL.md#installation
- https://github.com/sanger-pathogens/gubbins/issues/194 brew install gubbins errors - no formula for pillow

**Comment by tseemann** [comment]
@haruosuz try `brew install brewsci/science/gubbins`  for now

I am trying to migrate it to `brewsci/bio/gubbins` but having some problems with the setup.py

**Comment by haruosuz** [comment]
Thank you. I wonder if Gubbins can work on either Python 2 or Python 3? I used `Python 2.7.15 :: Anaconda, Inc.`
Typing `run_gubbins.py $FASTA_alignment` printed `RuntimeError: generator raised StopIteration`
Is there any tutorial for running Gubbins using example input and output data?

**Comment by tseemann** [comment]
http://sanger-pathogens.github.io/gubbins/
=>
https://github.com/sanger-pathogens/gubbins/raw/master/GubbinsManual_latest.docx

**Comment by haruosuz** [comment]
Thank you for providing the update manual. I confirmed 2. Requirements "Gubbins is a command line program designed to be run on Linux or Max OSX systems and requires Python version 2.7 or greater."

Using either Python 3.7.0 or Python 2.7.15, typing `run_gubbins.py core_gene_alignment.aln` printed `RuntimeError: generator raised StopIteration`. Then, typing `echo $?` printed `1`. I wonder how to resolve the exit status 1 error.
It generated the following Output files.
```
RAxML_bestTree.core_gene_alignment.iteration_1
RAxML_info.core_gene_alignment.iteration_1
RAxML_log.core_gene_alignment.iteration_1
RAxML_parsimonyTree.core_gene_alignment.iteration_1
RAxML_result.core_gene_alignment.iteration_1
core_gene_alignment.aln.gaps.phylip
core_gene_alignment.aln.gaps.snp_sites.aln
core_gene_alignment.aln.gaps.vcf
core_gene_alignment.aln.phylip
core_gene_alignment.aln.snp_sites.aln
core_gene_alignment.aln.start
core_gene_alignment.aln.vcf
```

**Comment by tseemann** [comment]
How did you install it?

The Python part of the latest version has been rewritten to simplify installation.

Are you still in a conda or brew or native system?
Mac or Linux?
What do these say:
```
which python
which python2
which python2.7
which python3
which python3.5
```

**Comment by haruosuz** [comment]
I installed Miniconda2 using:

	wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh
	bash Miniconda2-latest-MacOSX-x86_64.sh

I installed Miniconda3 using:

	wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
	bash Miniconda3-latest-MacOSX-x86_64.sh

I installed gubbins using:

	install brewsci/science/gubbins
	brew reinstall gubbins

I wonder how to check "Are you still in a conda or brew or native system?"

`which` said as follows:

```
~ $which python
/Users/haruo/miniconda3/bin/python
~ $which python2
/Users/haruo/miniconda2/bin/python2
~ $which python2.7
/Users/haruo/miniconda2/bin/python2.7
~ $which python3
/Users/haruo/miniconda3/bin/python3
~ $which python3.5
~ $uname -a
Darwin haruonoMacBook.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

I can use both Miniconda2 and Miniconda3 by editing `.bash_profile` on MacOS High Sierra 10.13.6.
```
# added by Miniconda2 installer
export PATH="/Users/haruo/miniconda2/bin:$PATH"

# added by Miniconda3 installer
export PATH="/Users/haruo/miniconda3/bin:$PATH"
```

Typing `run_gubbins.py core_gene_alignment.aln` printed `RuntimeError: generator raised StopIteration` for both miniconda3 and miniconda2.
