### ISSUE TITLE
Gubbins crashed, please ensure you have enough free memory

### ISSUE THREAD

**Issue by drahmadghazi** [nickjcroucher/gubbins#239]
Hi, 

After running Snippy to create the core alignment I ran Gubbins and got the following after few seconds 
(Gubbins crashed, please ensure you have enough free memory)

HELP!

**Comment by tseemann** [comment]
@drahmadghazi this was due to a RAM allocation bug. 
It was fixed in latest v2.3.4: https://github.com/sanger-pathogens/gubbins/releases/tag/v2.3.4
You will need to upgrade manually.

**Comment by drahmadghazi** [comment]
Thanks so much, I removed my current version that was installed through (sudo apt-get) and reinstalled via conda and now perfectly working. 
Thanks also for replying during the weekend! 
Have a nice day
