### ISSUE TITLE
some questions about the file ".filtered_polymorphic_sites.fasta" 

### ISSUE THREAD

**Issue by zhaoxvwahaha** [nickjcroucher/gubbins#243]
The description of this file is "FASTA format alignment of filtered polymorphic sties used to generate the phylogeny in the final iteration"
(1) what "filtered" means? It filtered the recombination regions of polymorphic sites?
(2) if it is recombination free file, why there are "N"s in this file, the N means recombination site, right? 
(3) Is the tree "final_tree.tre" constructed by this fasta file? can I used this fasta file in BEAST software?

Thanks in advance, looking forward to your reply.

**Comment by zhaoxvwahaha** [comment]
Hi，@satta @AidanDelaney ，I'll appreciate if you could answer above questions.

**Comment by satta** [comment]
I'm sure that @andrewjpage  or @AidanDelaney are more qualified to answer than I am ;)

**Comment by cizydorczyk** [comment]
I've been wondering the same thing recently but here is what I understand:

1) The filtered fasta file contains only polymorphic sites. It is filtered in that any polymorphic sites in the original alignment that were deemed to be in recombined regions are masked with 'N's.
2) It is a recombination-free file. But it only contains polymorphic sites.
3) Yes, it is the file used to create the final tree. I would not use the fasta for BEAST though; it contains only polymorphic sites, which can cause issues for BEAST.

See the user manual found here http://sanger-pathogens.github.io/gubbins/ for answers to your questions here as well.

**Comment by hy-zheng** [comment]
i want to run the beast after gubbins too,and i also don't know how to get the input_file (the alignment) after gubbins, have you solved the problem ?
