### ISSUE TITLE
Why is Gubbins 2.3.1 so slow? 

### ISSUE THREAD

**Issue by slvrshot** [nickjcroucher/gubbins#248]
Hi I have 116 Whole genomes that I initially ran through ParSNP and now I'm running through Gubbins to remove recombination. I am just curious why it is taking so long. It appears it is still on iteration 1 and its been running for over 24 hours.  Here is the command I used:

run_gubbins.py $dirpath/ParSNP/ParSNP_results/parsnp_multifasta.fasta -p gubbins --threads 32

**Comment by tseemann** [comment]
Did you try giving it a starting tree?
Does it still happen on 2.3.4 ?

**Comment by mabouelk** [comment]
Hi @tseemann 
I used snippy on about 339 isolates and then cleaned the core aln by using snippy-clean_full_aln. Then I used gubbins on the cleaned file but the run is very slow. How I can give it a starting tree as you mentioned or is there any way to make it run faster?

**Comment by tseemann** [comment]
That's a big alignment.  I suspect it is a species that is very recombinant, and gubbins may be having trouble to converge. You will need to give more information:
* 339 isolates :heavy_check_mark: 
* width of alignment? ie. genome size
* how many core SNPs?
* how many Ns per average in each sample?
* what species?

**Comment by mabouelk** [comment]
It is staphylococcus pseudintermedius, genome size on average 2.5 Mb each. How I can know the number of core SNPs and Ns?

**Comment by mabouelk** [comment]
Hi @tseemann 
please when you have time, help me with this?

**Comment by tseemann** [comment]
`fa -t -f -e core.full.aln | less -S` ?

**Comment by mabouelk** [comment]
thank you, I appreciate your time and valuable help. when I run that I got this error: 
fa: command not found

**Comment by tseemann** [comment]
I thought it came with nullarbor!

**Comment by mabouelk** [comment]
yes you are right, I did not activate the nullarbor env. 

here is the output 


PATRIC38.fna    dna     2766566
PATRIC4.fna     dna     2766566
PATRIC5.fna     dna     2766566
PATRIC50.fna    dna     2766566
PATRIC71.fna    dna     2766566
PATRIC78.fna    dna     2766566
PATRIC86.fna    dna     2766566
Reference       dna     2766566
SRR5875113.fna  dna     2766566
SRR5928603.fna  dna     2766566
SRR6118626.fna  dna     2766566
SRR6118627.fna  dna     2766566
SRR6118665.fna  dna     2766566
SRR6160719.fna  dna     2766566
SRR6160722.fna  dna     2766566
SRR6160723.fna  dna     2766566
SRR6214465.fna  dna     2766566
SRR6214501.fna  dna     2766566
SRR6214505.fna  dna     2766566
SRR6311178.fna  dna     2766566
SRR6312081.fna  dna     2766566
SRR6312082.fna  dna     2766566
SRR6312088.fna  dna     2766566
SRR6312205.fna  dna     2766566
SRR6312212.fna  dna     2766566
SRR6312289.fna  dna     2766566
SRR6374204.fna  dna     2766566
SRR6374214.fna  dna     2766566
SRR6424306.fna  dna     2766566
SRR6424470.fna  dna     2766566
SRR6424825.fna  dna     2766566
SRR6742561.fna  dna     2766566
SRR6742574.fna  dna     2766566
SRR6742584.fna  dna     2766566
SRR6795845.fna  dna     2766566
SRR6795874.fna  dna     2766566
SRR6795890.fna  dna     2766566
SRR6795894.fna  dna     2766566
SRR6814849.fna  dna     2766566
SRR6814918.fna  dna     2766566
SRR6814921.fna  dna     2766566
SRR6814922.fna  dna     2766566
SRR6978943.fna  dna     2766566
SRR7079317.fna  dna     2766566
SRR7239309.fna  dna     2766566
SRR7239977.fna  dna     2766566
SRR7638089.fna  dna     2766566
SRR7638094.fna  dna     2766566
SRR7647893.fna  dna     2766566
SRR7765187.fna  dna     2766566
SRR7765202.fna  dna     2766566
SRR7765206.fna  dna     2766566
SRR7788249.fna  dna     2766566
SRR7788256.fna  dna     2766566
SRR7788258.fna  dna     2766566
SRR8062140.fna  dna     2766566
SRR8062145.fna  dna     2766566
SRR8062147.fna  dna     2766566
SRR8092757.fna  dna     2766566
SRR8092758.fna  dna     2766566
SRR8092759.fna  dna     2766566
SRR8092760.fna  dna     2766566
SRR8092762.fna  dna     2766566
SRR8092763.fna  dna     2766566
SRR8092764.fna  dna     2766566
SRR8092765.fna  dna     2766566
SRR8092766.fna  dna     2766566
SRR8092767.fna  dna     2766566
SRR8092768.fna  dna     2766566
SRR8092769.fna  dna     2766566
SRR8092770.fna  dna     2766566
SRR8092771.fna  dna     2766566
core.full.aln   339     937865874       804777181       14249686        118839007       2766566 2766566 2766566 2766566
(END)

**Comment by tseemann** [comment]
I forgot to say `fa -e -f -t --bases`
