### ISSUE TITLE
How to know the specific regions that were extracted by Gubbins

### ISSUE THREAD

**Issue by Rathanin-github** [nickjcroucher/gubbins#256]

**Comment by Rathanin-github** [comment]
After running snippy using .gbk as reference, I run snippy core (snippy-core  --ref K9.gb samples*. Then I run run gubbin with core.full.aln (output file from snippy-core). I wounder how can I get the specific combination site (gene or GI) that gubbins has removed? Thanks in advance!

**Comment by tseemann** [comment]
1, you may want to use `snippy-clean_full_aln` before passing it to gubbins

2. https://github.com/sanger-pathogens/gubbins#output-files

3. you can use `bedtools intersect` with a GFF file of the original genome annotation AND the `.recombination_predictions.gff	` ?

**Comment by Rathanin-github** [comment]
Dear @tseemann 
Thanks for suggestion. I am working on it. I will update you after finishing my analysis.

**Comment by acpaulo** [comment]
Dear @Rathanin-github,

Did you manage to find a solution for your question? I have the same problem. 
I'm working with gff files that are ill annotated. So even if I visualize the results of gubbins in phanadango I don't get much information. On the other hand is a litlte bit time consuming to track recombinations in phandango. I would like very much to have a list with gene name and DNA sequence involved in recombinations. If I have the gene annotated good if not I can use the sequence to blast again a database and try to find the gene involved. If anyone know how to do this and can share will be very good. I', sorry I'm new in bioinformatics so maybe this is something simple to do. I tried the proposal from @tseemann with bedtools with no sucess. Thank you in advance.
