### ISSUE TITLE
The average values of r/m and rho/theta for the whole dataset

### ISSUE THREAD

**Issue by hngyou** [nickjcroucher/gubbins#257]
Hi,
I am using Gubbins to detect recombination in a dataset of Vibrio genomes . Gubbins gave values of r/m and rho/theta for each branch in output file ".per_branch_statistics.csv".

My question is : 
If I want to know the average values of both r/m and rho/theta of the whole dataset, is it a right way to calculate them as below:

r/m=(Sum of Num of SNPs inside recombinations) / (Sum of Num of SNPs outside recombinations)
rho/theta=(Sum of Num of Recombination Blocks) / (Sum of Num of SNPs outside recombinations)

THX.

[.per_branch_statistics.xlsx](https://github.com/sanger-pathogens/gubbins/files/3775610/default.per_branch_statistics.xlsx)

**Comment by moorembioinfo** [comment]
Hi @hngyou, did you resolve this issue? I was wondering myself whether it's appropriate to average over the leaf branch values and ignore internal node statistics (as they're cumulative over the tree)

Best, 

Matt
