### ISSUE TITLE
gubbins and parsnp

### ISSUE THREAD

**Issue by rpatnav** [nickjcroucher/gubbins#258]
Hello,

I am aware of the incompatibility of using gubbins on SNP alignments or on the core-gene-alignment from roary. However I am wondering whether we can use gubbins on the parsnp core genome alignment output in the case we used a complete genome as reference, since intergenic sequences are maintained. is it possible?

Thanks

**Comment by tseemann** [comment]
Does parsnp give a whole genome alignment in FASTA format with each  entry having the same length?
If so, then yes.
