### ISSUE TITLE
 snippy-clean_full_aln did not replace --- by N

### ISSUE THREAD

**Issue by Rathanin-github** [nickjcroucher/gubbins#262]
Hi @tseemann 
I have re-run snippy of short read (R1 and R2) against reference genome. after running snippy core, I got a core.full.aln that contain "----". I use  snippy-clean_full_aln to replace -- with N by snippy-clean_full_aln core.full.aln > clean.full.aln, but I still see "---" in my clean.full.aln. So, do ---  make trouble for my further analysis (gubbins, snp-sites, iqtree) and could you please suggest the solution for that?
Thanks in advance!

**Comment by Rathanin-github** [comment]
Here is the grep -c of N, n and - in core.full.aln and clean.full.aln: 

(base) nc-lab@DORIM2019:/mnt/c/Rathanin/test5/snippybp$ grep -c "N" core.full.aln
113150
(base) nc-lab@DORIM2019:/mnt/c/Rathanin/test5/snippybp$ grep -c "n" core.full.aln
28940
(base) nc-lab@DORIM2019:/mnt/c/Rathanin/test5/snippybp$ grep -c "-" core.full.aln
316283
(base) nc-lab@DORIM2019:/mnt/c/Rathanin/test5/snippybp$ grep -c "N" clean.full.aln
140540
(base) nc-lab@DORIM2019:/mnt/c/Rathanin/test5/snippybp$ grep -c "n" clean.full.aln
1
(base) nc-lab@DORIM2019:/mnt/c/Rathanin/test5/snippybp$ grep -c "-" clean.full.aln
316283

**Comment by tseemann** [comment]
I think this message is posted to the wrong repo? 
Anyway
```
snippy-clean_full_aln -h
SYNOPSIS
  Replace non-[AGTCN-] chars with 'N'
```
It never claimed to replace gaps.  Gubbins wants the gaps.

**Comment by Rathanin-github** [comment]
Hi @tseemann 
Thanks you for quick response and sorry for posting to the wrong repo.
