### ISSUE TITLE
Why some isolates are removed by Gubbins

### ISSUE THREAD

**Issue by zhaoxvwahaha** [nickjcroucher/gubbins#274]
I have 1500 aligned sequences in fasta file, but 5 of them are removed after Gubbins , there are 1495 isolates in ***filtered_polymorphic_sites.fasta** and ***final_tree.tre** files, anyone know the reason, are the 5 isoaltes  too divergent from others? Thanks in advance.

**Comment by tseemann** [comment]
Maybe `raxml` is rejecting outliers.

**Comment by zhaoxvwahaha** [comment]
@tseemann Thank you for your timely and helpful reply, do you know the rejecting rules, I don't found this information in the manual of Gubbins

**Comment by tseemann** [comment]
You should attempt to do some QC on your alignments before giving to gubbins.

eg. for each sequence, how many "N" are there?

**Comment by matbeale** [comment]
There is an automatic filter that removes sequences for which >25% of sites are missing/ambiguous ('N' or '-'). This is intended behaviour, since you don't want to be inferring recombination based on SNP density when a lot of those sites are actually missing.  You can tweak this parameter using the `-f` flag. As Torsten suggests, perhaps check the number of 'N' sites in your alignment for each sample.

**Comment by tseemann** [comment]
Does gubbins output these removals in the log output?
(i haven't run it in a while sorry!)

**Comment by matbeale** [comment]
Gubbins used to explicitly list the genomes removed by this filter in the log output/stdout (e.g. still shows up when running version 1.4.9). For more recent versions (e.g. v2.4.1) this message is no longer present. This may have been removed when gubbins was moved over to RAxML for ancestral reconstruction, but I'm not sure (and gubbins isn't being actively maintained anymore, unfortunately).

**Comment by victoriam0119** [comment]
Dear,
Have you been able to give an answer to this problem? I also have 2 genomes that are removed from my analysis
Thank you,

**Comment by nickjcroucher** [comment]
It will be due to these options likely:
```
  --filter-percentage FILTER_PERCENTAGE, -f FILTER_PERCENTAGE
                        Filter out taxa with more than this percentage of gaps (default: 25.0)
  --remove-identical-sequences, -d
                        Remove identical sequences (default: False)
```

**Comment by victoriam0119** [comment]
Thanks for your answer. 
I have tried with -f 30 but gubbins remains stagnant for several days in the first iteration and in the case of using -d must indicate TRUE? 
could you guide me? 
Best regards
