### ISSUE TITLE
Test failure on i386: ""No usable version of RAxML could be found."

### ISSUE THREAD

**Issue by tillea** [nickjcroucher/gubbins#276]
Hi,
the Debian packaged gubbins has trouble to use RaXML.  As you can see in the [complete build log](https://buildd.debian.org/status/fetch.php?pkg=gubbins&arch=i386&ver=2.4.1-1&stamp=1579695492&raw=0) it runs into

    ======================================================================
    ERROR: test_raxml_convert_raw_ancestral_states_to_fasta (gubbins.tests.test_treebuilders.TestStringConstruction)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/<<PKGBUILDDIR>>/python/gubbins/tests/test_treebuilders.py", line 91, in test_raxml_convert_raw_ancestral_states_to_fasta
        raxml = treebuilders.RAxML(8)
      File "/<<PKGBUILDDIR>>/python/gubbins/treebuilders.py", line 147, in __init__
        sys.exit("No usable version of RAxML could be found.")
    SystemExit: No usable version of RAxML could be found.

The i386 Debian package just contains /usr/bin/raxmlHPC but if I'm reading line 142 of file ``python/gubbins/treebuilders.py`` in gubbins source

    142         self.single_threaded_executables = ['raxmlHPC-AVX2', 'raxmlHPC-AVX', 'raxmlHPC-SSE3', 'raxmlHPC']
    143         self.multi_threaded_executables = ['raxmlHPC-PTHREADS-AVX2', 'raxmlHPC-PTHREADS-AVX',
    144                                            'raxmlHPC-PTHREADS-SSE3', 'raxmlHPC-PTHREADS']
    145         self.executable = self.select_executable_based_on_threads()
    146         if self.executable is None:
    147             sys.exit("No usable version of RAxML could be found.")
 
correctly this should be a valid single trheaded executable.
Any hint how we can pass the test suite also on i386?

Kind regards, Andreas.

**Comment by puethe** [comment]
Hi Andreas,
thanks for still building the debian package, this is great.
Looking at the tests, the number of threads is set to 8 (for whatever reason), so it's looking for one of the multi-threaded executables. Which means that you'd need to install one of them to get the tests passing. Is that a possible solution for you? Or alternatively, could you live with some broken tests? Gubbins should still run fine in single-threaded mode.
Best wishes,
Christoph
