### ISSUE TITLE
Whole-genome alignment or just polymorphic sites?

### ISSUE THREAD

**Issue by apredeus** [nickjcroucher/gubbins#279]
Hello, 

Does it make any difference whether we're using the full alignment or just polymorphic sites? I've read a discussion about the scale of the obtained tree. Would be nice to have a bit more clarity on this. 

Thank you in advance!

**Comment by matbeale** [comment]
Hi,

It definitely matters! Gubbins infers recombination partially based on SNP density within a given sliding window. Therefore inputting polymorphic sites (i.e. SNPs) would be expected to give (very) incorrect results. You need to give it a full genome length alignment, with nothing removed (although if you want to mask a small number of sites to 'N' due to low coverage/quality/MGEs, that's ok).

**Comment by wanyuac** [comment]
> due to low coverage/quality/MGEs, that's ok).

I agree with you. A pseudo-alignment of SNP sites works against the methodology of Gubbins.

**Comment by wanyuac** [comment]
> It definitely matters! Gubbins infers recombination partially based on SNP density within a given sliding window. Therefore inputting polymorphic sites (i.e. SNPs) would be expected to give (very) incorrect results. You need to give it a full genome length alignment, with nothing removed (although if you want to mask a small number of sites to 'N' due to low coverage/quality/MGEs, that's ok).

I agree with you. A pseudo-alignment of SNP sites works against the methodology of Gubbins.

**Comment by deeptir-unimelb** [comment]
> Hi,
> 
> It definitely matters! Gubbins infers recombination partially based on SNP density within a given sliding window. Therefore inputting polymorphic sites (i.e. SNPs) would be expected to give (very) incorrect results. You need to give it a full genome length alignment, with nothing removed (although if you want to mask a small number of sites to 'N' due to low coverage/quality/MGEs, that's ok).

So it would be incorrect if the core.aln file (which is core snp alignment) from SNIPPY is used for Gubbins? 
I found this paper (https://www.sciencedirect.com/science/article/pii/S1473309913706935) in which they have done that and I'm confused. Thanks in advance!

**Comment by nickjcroucher** [comment]
@deeptir-unimelb That analysis was run on a whole genome alignment. The way to combine snippy and Gubbins is as suggested here: https://github.com/tseemann/snippy.
