### ISSUE TITLE
Different Reference genomes give different recombination results

### ISSUE THREAD

**Issue by Cythrawl10** [nickjcroucher/gubbins#284]
Hello,

Please forgive my ignorance but I am not a programmer, rather I have a team of bioinformaticts that regualry compare bacterial genomes for outbreak work. We have always used Gubbins to help filter out recombination and get more accurate SNP calls, but I have noticed a trend where depending on what reference genome you select, you can get significantly different results. For the most part I am referring to isolates that are already quite related (<10 allelic differences with cgMLST for example), so the SNP differneces are already quite small.  I've attached an Excel file showing these differences in a comaprison of seven closely related isolates. In one set, Isolate 1 is the refernce (in red) and in the other, isolate 6 is the reference. As you can imagine, this is a significant difference for outbreak work.  I'm trying to get my head around why this might happen, but any insights from those of you that use this on a regular basis, and might have come across this issue in the past, would be greatly appreciated.
[SNP Calls - Pre and Post Gubbins - Github.xlsx](https://github.com/sanger-pathogens/gubbins/files/5142136/SNP.Calls.-.Pre.and.Post.Gubbins.-.Github.xlsx)

**Comment by nickjcroucher** [comment]
This is a consequece of mapping and alignment unfortunately - Gubbins will change its mind when the data change.
