### ISSUE TITLE
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error

### ISSUE THREAD

**Issue by tillea** [nickjcroucher/gubbins#286]
Hi,
the Debian packaged version of gubbins stopped building which you can see in the according [bug report](https://bugs.debian.org/971111).  I was seeking for help with this issue at the Debian Python team but the [answer](https://bugs.debian.org/971111#10) recommends to ask the developers:

    python/gubbins/common.py::parse_and_run() constructs an absolute path for
    the executable and then passes it to pkg_resources.get_distribution(). I
    have no idea what does this code want to achieve, as get_distribution()
    takes requirement specifications, not file paths.

Kind regards, Andreas.

**Comment by puethe** [comment]
Hi Andreas,

development on Gubbins has come to a stop, the software is no longer actively maintained as we don't have the resources for it. So I'm happy for you to take it off the list for debian packaging. I will keep this issue open though to address the problem if/when we get back to Gubbins development.

Best wishes,
Christoph

**Comment by tillea** [comment]
Hi Christoph,

On Fri, Oct 30, 2020 at 04:19:36AM -0700, Christoph Püthe wrote:
> development on Gubbins has come to a stop, the software is no longer actively maintained as we don't have the resources for it. So I'm happy for you to take it off the list for debian packaging. I will keep this issue open though to address the problem if/when we get back to Gubbins development.

Ahhh, that's bad news.  Since there are definitely active users of Gubbins in the Debian community I'll keep on trying finding a fix for this.
Kind regards, Andreas.

**Comment by nickjcroucher** [comment]
Hi @tillea - I have re-started some work on Gubbins on a fork (https://github.com/nickjcroucher/gubbins) - before I make any substantial changes to the architecture of the software, would you like any of the patches integrated from your version? Also, could you let me know which files you use in your packaged version? Thanks!

**Comment by tillea** [comment]
On Fri, Dec 18, 2020 at 03:01:32AM -0800, nickjcroucher wrote:
> Hi @tillea - I have re-started some work on Gubbins on a fork (https://github.com/nickjcroucher/gubbins) - before I make any substantial changes to the architecture of the software, would you like any of the patches integrated from your version?

Feel free to inspect all Debian patches here:
  https://salsa.debian.org/med-team/gubbins/-/tree/master/debian/patches

> Also, could you let me know which files you use in your packaged version? Thanks!

I'm not sure what exactly you are asking for.  May be you want to check a binary package you can download here:
  https://packages.debian.org/sid/amd64/gubbins/download
Debs can be viewed with modern file browsers usually.

Hope this helps, Andreas.

**Comment by nickjcroucher** [comment]
Thanks! Sorry, I was rushing to a meeting and not being clear at all - we may be changing the structure of the software and the installation of package dependencies, and if there are any Debian-specific considerations, please let me know. Else I will incorporate the patches and do my best not to make life more difficult for you.

**Comment by tillea** [comment]
On Fri, Dec 18, 2020 at 03:46:53AM -0800, nickjcroucher wrote:
> Thanks! Sorry, I was rushing to a meeting and not being clear at all - we may be changing the structure of the software and the installation of package dependencies, and if there are any Debian-specific considerations, please let me know. Else I will incorporate the patches and do my best not to make life more difficult for you.

Sounds very good to me, Andreas.
