### ISSUE TITLE
core or whole genome result produced by gubbins?

### ISSUE THREAD

**Issue by Lneffe** [nickjcroucher/gubbins#292]
Hi! 
my question might be a bit obvious still I have some problems understanding the topic, whenn attending the paper. 

Gubbins uses a Whole Genome File as input. 
Also the tree building algorithm (RAxML in my case)  uses this file as input and constructs the tree from it. 
The recombinant regions are then masked and subsequently excluded. 
However the final alignment, which is much shorter, contains what kind of positions? 

Could one say it contains only core genome postions that are left?
I suppose also the final tree is based on this alignment. 

Thanks in advance!

**Comment by nickjcroucher** [comment]
That's right, the `filtered_polymorphic_sites.phylip` file will contain the filtered alignment used to construct the final tree.

**Comment by matbeale** [comment]
@nickjcroucher On this subject, I've been thinking for a while it might be worth including an option to output a full length masked WGS alignment in future iterations of gubbins. Many in the community have workaround scripts, but it still feels odd to not include this output as part of Gubbins. Building a subsequent IQ-Tree or BEAST analysis will usually need a full length alignment, or at least the invariant sites...

**Comment by nickjcroucher** [comment]
@matbeale this is a very good idea, I've been updating the code (https://github.com/nickjcroucher/gubbins/issues/1) and will add this in - at least with the current version of the upgrade, it should already be possible to run IQTREE directly within Gubbins. Also consider BactDating as an alternative to BEAST for Gubbins outputs: https://xavierdidelot.github.io/BactDating/articles/yourData.html.

**Comment by nicolettacommins** [comment]
@matbeale I am also in need of a full length masked alignment for something I want to do. In the past I've been able to add workarounds to BEAST but now I actually need to know the position of each SNP in the alignment relative to my original reference sequence. You mentioned that many have workaround scripts, do you have a general idea of what people usually do  to get around this? The only thing I can think of is taking all the recombination predictions and writing a script to mask those regions in every isolate downstream of that recombination event.

**Comment by nickjcroucher** [comment]
@matbeale and @nicolettacommins I've added a script for masking alignments in the `python/scripts` directory on the `masking_aln` branch - let me know if it works for you.

**Comment by tanusaroha** [comment]
I have same issue as @matbeale and @nicolettacommins . I tried looking for script as @nickjcroucher suggested but i could not find that script in python directory. @nickjcroucher can you please elaborate on this. Also, the final fasta file generated is not the whole length recombination region masked alignment, it just has polymorphic filtered sites(not complete alignment), if i have understood that correctly.  If i need to generate a recombination free phylogeny using gubbins output which file should i use?

**Comment by nickjcroucher** [comment]
@tanusaroha are you on the `masking_aln` branch? The script can be found here: https://github.com/sanger-pathogens/gubbins/blob/masking_aln/python/scripts/mask_gubbins_aln.py

**Comment by tanusaroha** [comment]
@nickjcroucher Thank you for information. I am able to find the script.

**Comment by tanusaroha** [comment]
@nickjcroucher Are you planning to give one of the output file contatining full length masked (snp in recombination region masked) WGS alignment in future versions of gubbins?

**Comment by nickjcroucher** [comment]
@tanusaroha Not by default, because my thinking was that many people won't need it, and it may essentially duplicate a large file. Happy to hear alternative opinions though. I will update the documentation once we've finalised the new version of the code.

**Comment by s4251484** [comment]
i second @matbeale, @nicolettacommins and @tanusaroha. Here to express the need for the exact SNP positions on the reference genome instead of the core alignment. Thanks!

**Comment by nickjcroucher** [comment]
@s4251484 I'm not sure what the problem is to which you are referring - the SNP positions refer to the whole genome alignment (Gubbins should not be used on a core genome alignment), as there is no "reference" sequence as far as Gubbins is concerned.

**Comment by s4251484** [comment]
> @s4251484 I'm not sure what the problem is to which you are referring - the SNP positions refer to the whole genome alignment (Gubbins should not be used on a core genome alignment), as there is no "reference" sequence as far as Gubbins is concerned.
@nickjcroucher thanks for your reply!
Apologies - I was referring to the whole genome alignment. i wish to see the location of the SNPs (after parsnp + gubbins + SNPEFF filtering) at each of the strain genomes.  but anyways - I'm not even sure if this is beneficial.

i ran mask_gubbins_aln.py on the alignment file generated from parsnp, each fasta entry in the miltu-fasta file still have the same length as before mask_gubbins_aln.py but now different in GC (I checked with emboss infoseq) - just wanna check with you if this is what I should be expecting? thanks!

**Comment by matbeale** [comment]
That is what I would expect the script to do - you should be getting an alignment of the same length, but with some bases inferred as under recombination masked to 'N', hence it is expected to have a slightly different GC content.

**Comment by nickjcroucher** [comment]
@s4251484 as @matbeale says, that's the expected output, hope it's helpful!
