### ISSUE TITLE
New gubbins version install issue

### ISSUE THREAD

**Issue by MartaMatu** [nickjcroucher/gubbins#296]
I'm trying to update my gubbins to a new version of gubbins (2.3.4). I was having some issues with getting the non-specific error regarding memory. I used apt-get and from source install but the version installed is still 2.3.1. Could you suggest any solution?

**Comment by nickjcroucher** [comment]
I would recommend using conda: https://anaconda.org/bioconda/gubbins

**Comment by MartaMatu** [comment]
Apologies but we don't use conda on our server.

**Comment by nickjcroucher** [comment]
In which case you could remove the existing install and re-install, it might be that the existing files are blocking the new version. Else clone the git repository and use the instructions for installing using `make` to install from source.

**Comment by MartaMatu** [comment]
Thank you so much, that worked!

**Comment by nickjcroucher** [comment]
Excellent, enjoy your recombination analyses!
