### ISSUE TITLE
raxml-ng-mpi not in path

### ISSUE THREAD

**Issue by josemunozc** [nickjcroucher/gubbins#297]
Hi, not sure if this is an issue but thought of mentioning it. I noticed that when selecting '--tree-builder raxmlng', gubbins tests if an executable with AVX2, AVX or SSE3 in the name exists in the path:

utils.py
```
111     if cpu_info:
112         # Iterate through list to match with CPU features
113         for executable in list_of_executables:
114             if 'AVX2' in executable and 'avx2' in flags and which(executable):
115                 break
116             elif 'AVX' in executable and 'avx' in flags and which(executable):
117                 break
118             elif 'SSE3' in executable and 'sse3' in flags and which(executable):
119                 break
120     else:
121         # Final executable on list is generic
122         executable = list_of_executables[-1]
```

Which seems to be expected if working with raxml (the default)

treebuilders.py
```
413         self.single_threaded_executables = ['raxmlHPC-AVX2', 'raxmlHPC-AVX', 'raxmlHPC    -SSE3', 'raxmlHPC']
414         self.multi_threaded_executables = ['raxmlHPC-PTHREADS-AVX2', 'raxmlHPC-PTHREAD    S-AVX',
415                                            'raxmlHPC-PTHREADS-SSE3', 'raxmlHPC-PTHREAD    S']
```

but not for raxmlng which will always fail the test, falling back to the last item in the list (raxml-ng):

treebuilders.py
```
620         self.single_threaded_executables = ['raxml-ng']
621         self.multi_threaded_executables = ['raxml-ng-mpi','raxml-ng']
```

Problem is that I do have 'raxml-ng-mpi' in the path but since the test is failed and and the default option is set to 'raxml-ng' which is not in the path, Gubbins fails. For now I can work around it by creating a symlink, but I think having the option to specify the executable name could be useful.

**Comment by nickjcroucher** [comment]
@zerpiko - this seems like a bug - I've put a fix on the `masking_aln` branch, where I am adding some new scripts, with commit 32bf544:
https://github.com/sanger-pathogens/gubbins/blob/32bf5443d65f99cb2df78a852750d2d30285aca7/python/gubbins/utils.py#L112-L122
Can you let me know if this works?
