### ISSUE TITLE
run_gubbins.py: error: unrecognized arguments: --tree_builder hybrid

### ISSUE THREAD

**Issue by actledge** [nickjcroucher/gubbins#298]
my command:
run_gubbins.py  -p gubbins clean.full.aln --tree_builder hybrid

I have installed gubbins3.0.0 with conda,but when I try to use the parameter "--tree_builder", this error raised:
run_gubbins.py: error: unrecognized arguments: --tree_builder hybrid

**Comment by nickjcroucher** [comment]
This has been depreciated in v3.0.0, but the documentation has not been updated pending us completing testing, sorry - you can install v2.4.1 and this should work if you change the command to `run_gubbins.py -p gubbins clean.full.aln --tree-builder hybrid`. Or you can look at the new options available in v3 (`run_gubbins.py -p gubbins clean.full.aln --first-tree-builder fasttree --tree-builder raxml` should do what you expect).

**Comment by nickjcroucher** [comment]
Documentation now updated, sorry for the delay.
