### ISSUE TITLE
Gubbins to produce VCF of SNPs which go into tree

### ISSUE THREAD

**Issue by flashton2003** [nickjcroucher/gubbins#299]
It would be very helpful if gubbins could output a VCF of the SNPs which go into the final phylogenetic tree building step.

**Comment by nickjcroucher** [comment]
Hi @flashton2003 - thanks for the suggestion - if it's helpful in the meantime, there's a `masking_aln` branch with a script for generating an alignment with the recombinations stripped out (https://github.com/sanger-pathogens/gubbins/blob/masking_aln/python/scripts/mask_gubbins_aln.py), and you can use snp-sites to extract a VCF of the SNPs (http://sanger-pathogens.github.io/snp-sites/). Hope that's useful!

**Comment by flashton2003** [comment]
Hi Nick, thanks for the suggestion - that's exactly the approach I ended up coding up myself yesterday :-)

**Comment by nickjcroucher** [comment]
Super, glad you were one step ahead!
