### ISSUE TITLE
Gubbins and snippy usage - best way of combining these tools [help]

### ISSUE THREAD

**Issue by andreaniml** [nickjcroucher/gubbins#304]
Hello! It's my first time using gubbins and I have some questions, maybe they're silly:

1) Is there anyway that I could get the recombination-corrected tree made by gubbins with bootstrap support?
2) I'm trying to use gubbins with snippy, on the snippy github page there is a suggestion to use this:
snippy-clean_full_aln core.full.aln > clean.full.aln
However, here on the issues tab there is some discussion on using whole genome alignments, is this "core.full.aln" file ok to use?
3) This one is out of curiosity and  I understand if it is not the right site to ask, but on the snippy github site there's also a recommendation to use snp-sites on the filtered_polymorphic_sites.fasta output of gubbins and then generate the tree with the snp-filtered alignment. (snp-sites -c gubbins.filtered_polymorphic_sites.fasta > clean.core.aln \ % FastTree -gtr -nt clean.core.aln > clean.core.tree ; I would use iqtree or raxml instead of FastTree)
Why is it so? My guess is that it reduces the time needed to run the tree, however, does it change the results? 

If it not asking too much, do you have any recommendations where to read about "best practices" for snp phylogenies?

Thank you so much for any answers!

**Comment by nickjcroucher** [comment]
Hi @andreaniml:
1. the Gubbins tree output at the end can be annotated with support at each node using bootstrap information - the latest version also allows for transfer bootstraps or SH tests to be run to assess the support of each node.
2. `core.full.aln` looks to be the appropriate file to use from snippy - if Torsten Seemann recommends it, then it's probably a very sensible suggestion. I've added a script for making input alignments with SKA as well in the latest version of Gubbins.
3. just makes the calculation faster. A slightly controversial area beyond the scope of this question!

Hope that helps, Nick.

**Comment by andreaniml** [comment]
Thanks! It helped!
