### ISSUE TITLE
Error: could not convert COH.fasta to FASTA format

### ISSUE THREAD

**Issue by Sthandeka** [nickjcroucher/gubbins#313]
I have a problem with gubbins. I keep getting this error message. I tried to access the path but i get permission denied. Please help.

Saving reference FASTA: core.ref.fa
Unknown option: f
ERROR: Could not convert COH.fasta to FASTA format
Can't open core.full.aln: No such file or directory at /home/linuxbrew/.linuxbrew/opt/bioperl/libexec/lib/perl5/Bio/Root/IO.pm line 599.There is a problem with your input fasta file so nothing can be done until you fix it

**Comment by nickjcroucher** [comment]
This is a problem with Bioperl, not Gubbins.
