### ISSUE TITLE
A question, about wether to use clean.core.aln or gubbins.filtered_polymorphic_sites.fasta for a phylogentic tree.

### ISSUE THREAD

**Issue by actledge** [nickjcroucher/gubbins#317]
As I understand it,
The “snpsite -c” from Snippy，Will remove all sites with recombination, even if only one strain has recombination events at that site.
And for the gubbins.filtered_polymorphic_sites.fasta, it retains the information of strains without a recombination event in corresponding sites. And popular tree builders will use these informations regardless of the "N".

It seems that "snpsite -c" will remove a lot of useful information,  although it will acclerate the tree building.
I'm a relative novice, I don't quite understand the main purpose of using snpsite -c ,
and whether it will improve or decrease the accuracy of the tree.

Maybe there's something I haven't considered. I wondering，
for gubbins.filtered_polymorphic_sites.fasta and clean.core.aln，
 which is more suitable for tree construction if I wanted a relative accurate tree.

(and, the clean.core.aln produced a obviously or somewhat werid tree for my datasets, 
and  also for subset with only one serotype and sequence type, with RAxML or IQTree.
But gubbins.filtered_polymorphic_sites.fasta produced a tree that looked more reasonable.)

**Comment by nickjcroucher** [comment]
I don't know what Snippy snpsite does, but you're correct that the masked alignment, or filtered SNP set, is more phylogenetically informative than a cleaned set, where any column containing missing data has been removed. Gubbins will produce a tree from the masked alignment, which will save you the effort of drawing your own tree afterwards, unless there's a specific reason for futher phylogenetic analysis?

**Comment by actledge** [comment]
> I don't know what Snippy snpsite does, but you're correct that the masked alignment, or filtered SNP set, is more phylogenetically informative than a cleaned set, where any column containing missing data has been removed. Gubbins will produce a tree from the masked alignment, which will save you the effort of drawing your own tree afterwards, unless there's a specific reason for futher phylogenetic analysis?

Thank you very much for your reply.
In fact, I'm not quite sure what the advantage of using Gubbins' output to rebuild a phylogenetic tree would be. Mainly because I've seen some of the articles quoted Gubbins and people I've consulted both to use Snippy to clean them up first and get reliable results in their data sets. And the code in the Snippy documentation seems to suggest that. 
And, embarrassingly, I may have been mistaken, subconsciously assuming that there was some overlap between gubbins' developers and Snippy's, although there wasn't.
Anyway, I had therefore assumed that rebuilding the tree using Gubbins' output might be necessary to get a more accurate tree. Although gubbins' original output tree did seem to make more sense in my dataset, I had been a little unsure.
Your reply has really solved the problem I've been struggling with,
Thanks again.

**Comment by actledge** [comment]
now I closed this Issue.
