### ISSUE TITLE
Gubbinsv3.1.4 hash symbol # to dash symbol _

### ISSUE THREAD

**Issue by daddysloth** [nickjcroucher/gubbins#320]
Gubbins v3.1.4 is omitting hash symbol `#` to dash symbol `_` when trimming alignment files from SKA etc., which should be fine as long as other upstream inputs, for instance, `nwk` tree files from PopPUNK etc. are consistently trimming `#` to `_` as well, or with no such symbols at all. However, some samples are easier to be identified with `#` symbol, for example, `12345_6#7` rather than `12345_6_7`

**Comment by nickjcroucher** [comment]
Hopefully fixed and tested in 359c16c, will update when when included in a new release.

**Comment by daddysloth** [comment]
Thanks for updates! `#` symbol in the file name is not omitted in SKA alignment anymore, however in the output, e.g., `.tre` files etc., hash `#` is replaced by underscore `_`
