### ISSUE TITLE
mask_gubbins_aln.py

### ISSUE THREAD

**Issue by xuechunxu** [nickjcroucher/gubbins#321]
Hi，

When I used mask_gubbins_aln.py to mask recombination regions:
`python ~/.conda/envs/gubbins-env/bin/mask_gubbins_aln.py --aln clean.full.aln --gff gubbins.recombination_predictions.gff --out clean.full.masked.aln`
It called an error:
`~/.conda/envs/gubbins-env/lib/python3.9/site-packages/Bio/Seq.py:1754: BiopythonDeprecationWarning: myseq.tomutable() is deprecated; please use MutableSeq(myseq) instead.
  warnings.warn(`

**Comment by xuechunxu** [comment]
It works after I installed biopython 1.78 instead of 1.79. However, nothing has changed in the `out.masked` file after running mask_gubbins_aln.py.

**Comment by amymariecampbell** [comment]
I'm getting this error too- did you find any solutions?

**Comment by nickjcroucher** [comment]
This is just a warning, the output should be fine unless there is another error - we will update this code soon.

**Comment by amymariecampbell** [comment]
Great- thank you!
