### ISSUE TITLE
Unable to build a hybrid tree in v3.0.0

### ISSUE THREAD

**Issue by UzmaBasit** [nickjcroucher/gubbins#326]
I am trying to build a hybrid tree using -t hybrid flag in my command but its generating following error

**elif input_args.model not in tree_models[input_args.tree_builder]:
KeyError: 'hybrid'**

Any suggestions to sort this issue?

**Comment by nickjcroucher** [comment]
This approach has been depreciated, you can use `--first-tree-builder fasttree --tree-builder raxml` instead - see the [manual](https://github.com/nickjcroucher/gubbins/blob/master/docs/gubbins_manual.md).
