### ISSUE TITLE
Coordinates in  the output file "Recombination predictions in GFF format"

### ISSUE THREAD

**Issue by valery-shap** [nickjcroucher/gubbins#330]
Hello,
Thank you for the great tool.
Sorry if my question is obvious but I couldn't find the answer in manual or issues.
Are the coordinates of .recombination_predictions.gff file correspond to the alignment file that was used for input? not the coordinates of the reference genome.
Valery

**Comment by nickjcroucher** [comment]
Apologies this wasn't clearer - the positions are relative to the alignment, not the reference sequence. Gubbins treats all sequences equally (i.e. it is not aware of a reference).

**Comment by nickjcroucher** [comment]
Clarified in manual in a2abf61.
