### ISSUE TITLE
Question: r/m calculation with CI95%!

### ISSUE THREAD

**Issue by Tonny-zhou** [nickjcroucher/gubbins#333]
Hello,

Thanks for this great tool to detect the recombination events in the bacterial genome！

I have obtained the r/m values in the gubbins.per_branch_statistics.csv file,  and next I want to calculate the 95% CI for some clades in the phylogenetic trees. Could you please tell me how to calculate it in R or something like?

Yours,
Tonny

**Comment by nickjcroucher** [comment]
I would recommend bootstrapping the branches - i.e. resampling with replacement - and recalculating the r/m to get CIs. The irregular distribution of mutations/variation across the tree means there isn't an easy analytical or distribution-based answer to this I'm afraid.

**Comment by Tonny-zhou** [comment]
Thanks for your timely response！ Acutally, i am a beginner in the field of phylogenetic analysis. Could you please tell me how to use the gubbins to perform this bootstraping process?

**Comment by nickjcroucher** [comment]
You can't do it in Gubbins, you need to use statistical software like R (e.g. https://www.statmethods.net/advstats/bootstrapping.html, https://towardsdatascience.com/a-practical-guide-to-bootstrap-with-r-examples-bd975ec6dcea) - good luck!
