### ISSUE TITLE
Gubbins not showing full data when adding a reference. help asap please

### ISSUE THREAD

**Issue by ragheedk** [nickjcroucher/gubbins#336]
Gubbins recombination tool via galaxy platform viewed on phandango. why is it when i add the annotation file i get half of my data with no recombination result as u can observe?? please help
<img width="1280" alt="Screen Shot 2022-04-04 at 1 56 05 PM" src="https://user-images.githubusercontent.com/102372976/161542456-dd09e790-b1aa-457c-b9a8-98b2752c0c18.png">

**Comment by ragheedk** [comment]
as you can see the right side is empty

**Comment by nickjcroucher** [comment]
Looks like you might be using a polymorphic site input alignment rather than a whole genome input alignment?

**Comment by ragheedk** [comment]
> Looks like you might be using a polymorphic site input alignment rather than a whole genome input alignment?

im using my whole genome sequencing data in gff fomat to run roary on galaxy platform then run gubbins from the roary output

**Comment by nickjcroucher** [comment]
Yep, that's the problem - this issue is described by the wise Andrew Page here: https://github.com/sanger-pathogens/Roary/issues/267 (see also http://nickjcroucher.github.io/gubbins/)

To generate a whole genome alignment, you can follow this guide: https://github.com/nickjcroucher/gubbins/blob/master/docs/gubbins_tutorial.md

**Comment by ragheedk** [comment]
> Yep, that's the problem - this issue is described by the wise Andrew Page here: [sanger-pathogens/Roary#267](https://github.com/sanger-pathogens/Roary/issues/267) (see also http://nickjcroucher.github.io/gubbins/)
> 
> To generate a whole genome alignment, you can follow this guide: https://github.com/nickjcroucher/gubbins/blob/master/docs/gubbins_tutorial.md

what if i am using it via the galaxy platform, any tutorials for that?

**Comment by nickjcroucher** [comment]
Sorry, I've never used Galaxy
