### ISSUE TITLE
Running raxML without -AVX2 options

### ISSUE THREAD

**Issue by slmiles** [nickjcroucher/gubbins#337]
Hi, 

I keep getting the error below when running gubbins

Illegal instruction (core dumped)
 Command 'raxmlHPC-PTHREADS-AVX2 -T 4 -safe -m GTRGAMMA -s core.full.aln.snp_sites.aln -n core.full.iteration_1_reconstruction -t /home/ubuntu/slm/gubbins/tmp382_i35u/core.full.iteration_1.tre.rooted -f e -w /home/ubuntu/slm/gubbins/tmp382_i35u' returned non-zero exit status 132.

**I understand that it might be because my server doesn't support AVX2. I have installed the standard version of raxML but it is still calling the AVX2 version. Is there a way to change this?** 

Thank you!

**Comment by nickjcroucher** [comment]
What version of Gubbins are you using?

**Comment by slmiles** [comment]
It's version 3.2.0.

**Comment by nickjcroucher** [comment]
Thanks - what operating system?

**Comment by slmiles** [comment]
An Ubuntu server. Thank you!

**Comment by nickjcroucher** [comment]
The function is here: https://github.com/nickjcroucher/gubbins/blob/a9d5dcddc2907c87f695eae86805d12959090f12/python/gubbins/utils.py#L97 Is AVX2 listed in the output of `grep flags /proc/cpuinfo`?

**Comment by slmiles** [comment]
AVX2 isn't listed but AVX is.

Thank you for your help.

**Comment by nickjcroucher** [comment]
Thanks - I see the bug, I'll try to fix ASAP - in the mean time, if you can delete raxmlHPC-PTHREADS-AVX2 and leave raxmlHPC-PTHREADS-AVX, that should work - else IQTREE2 will give similar results.

**Comment by slmiles** [comment]
Great, thank you!
