### ISSUE TITLE
Typo in manual: .final_tree.tree

### ISSUE THREAD

**Issue by ezherman** [nickjcroucher/gubbins#339]
Hi,

I noticed that the manual mentions a file with extension `.final_tree.tree` should be in the output. However, I found the file to have extension `.final_tree.tre` in practice. This gave me issues when integrating Gubbins in my workflow. 

Cheers,
Ezra

**Comment by nickjcroucher** [comment]
Thanks for spotting this, fixed in [ab18e3d](https://github.com/nickjcroucher/gubbins/commit/ab18e3dc0e68bfd102e34fb26ba0752ee3e1ec48), will be corrected in v3.2.2.
