### ISSUE TITLE
Can gubbins be used as a replacement for hyphy GARD or 3seq?

### ISSUE THREAD

**Issue by phiweger** [nickjcroucher/gubbins#340]
When run on a nucleotide (codon) alignment, is `gubbins` substantially different from GARD and `3seq`? I thought not, but then saw that in [this PNAS pneumococci paper](https://www.pnas.org/doi/10.1073/pnas.1613937114#sec-3) the authors of gubbins use `3seq` for this:

> To reduce any biases introduced by recombination, the codon alignments were scanned for breakpoints. The initial scan was performed with 3SEQ ... --

**Comment by nickjcroucher** [comment]
Gubbins is very different to GARD and 3seq in how it detects recombination - Gubbins is not appropriate for detecting exchanges between donors and recipients within an alignment of species-wide diversity (as in the PNAS paper), but is instead designed for detecting the import of diversity into a strain.

**Comment by phiweger** [comment]
Thanks for clarifying @nickjcroucher

**Comment by phiweger** [comment]
@nickjcroucher do I understand correctly that the `--pairwise` flag does allow the exchanges between donors and recipients?

**Comment by nickjcroucher** [comment]
You can use `--pairwise` to search for recombinations where the recipient sequence is known, as in https://doi.org/10.1101/2022.09.21.508813.
