### ISSUE TITLE
Description of extensive-search mode?

### ISSUE THREAD

**Issue by nicolettacommins** [nickjcroucher/gubbins#343]
I'm not able to find in the manual a description of what is happening in the extensive-search mode? Could the developers provide a quick explanation about what exactly is different compared to the default mode? Thanks!

**Comment by nickjcroucher** [comment]
It's a small change to the search strategy for recombinations - by default, Gubbins will use a threshold number of SNPs to identify recombinations. This used to sometimes be higher than the minimum number of SNPs in a recombination; that's now been changed, such that the threshold starts at the previous default, but is then decreased (the new default behaviour), or the threshold starts as the minimum number of SNPs (with the `--extensive-search` flag). I don't think the `--extensive-search` makes a big difference on most bacterial datasets. I'll add this to the manual.
