### ISSUE TITLE
generate_ska_alignment.py problem

### ISSUE THREAD

**Issue by aslangabriel** [nickjcroucher/gubbins#347]
Hi，I prepared fastq-list files as follows 
JSAHVC01R1	/home/work/APECSRA/JSAHVC01R1.fastq
JSAHVC01R2	/home/work/APECSRA/JSAHVC01R2.fastq
JSAHVC02R1	/home/work/APECSRA/JSAHVC02R1.fastq
JSAHVC02R2	/home/work/APECSRA/JSAHVC02R2.fastq
JSAHVC03R1	/home/work/APECSRA/JSAHVC03R1.fastq
JSAHVC03R2	/home/work/APECSRA/JSAHVC03R2.fastq
JSAHVC04R1	/home/work/APECSRA/JSAHVC04R1.fastq
JSAHVC04R2	/home/work/APECSRA/JSAHVC04R2.fastq
JSAHVC05R1	/home/work/APECSRA/JSAHVC05R1.fastq
JSAHVC05R2	/home/work/APECSRA/JSAHVC05R2.fastq
JSAHVC06R1	/home/work/APECSRA/JSAHVC06R1.fastq
JSAHVC06R2	/home/work/APECSRA/JSAHVC06R2.fastq, with python editon of 3.6.X. The command line is "python generate_ska_alignment_.py --reference ./CP004009_1.fasta --fastq fastqlist.txt --out APEC.aln"

But  it prompted the errot that"Traceback (most recent call last):
  File "generate_ska_alignment_.py", line 126, in <module>
    if os.path.isfile(info[1]) and os.path.isfile(info[2]):
IndexError: list index out of range
".
I have no idea what't the problem. Would you mind fixing it ?

**Comment by nickjcroucher** [comment]
The forward and reverse FASTQs need to be on the same line. e.g.:
`JSAHVC01R1 /home/work/APECSRA/JSAHVC01R1.fastq /home/work/APECSRA/JSAHVC01R2.fastq`

I should allow for single FASTQ files generally though.

**Comment by aslangabriel** [comment]
Thanks for your help. By the way for fastq list,  am I right to set three columns separated by tab with ID R1path R2 path?
