### ISSUE TITLE
mask_gubbins_aln.py issue

### ISSUE THREAD

**Issue by Dangoh** [nickjcroucher/gubbins#348]
Hi,

I have problems running mask_gubbins_aln.py and get an error saying:

Traceback (most recent call last):
  File "mask_gubbins_aln.py", line 71, in <module>
    taxon.seq = MutableSeq(taxon.seq)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/Bio/Seq.py", line 1663, in __init__
    "The sequence data given to a MutableSeq object "

My input is basically the alignment I had for gubbins in .fasta format and the .gff from gubbins as below:

python3.6 ~/tools/gubbins/python/scripts/mask_gubbins_aln.py --aln /mnt/eg/gubbins/eg_13-20/all_eg.fasta --gff /mnt/eg/gubbins/eg_13-20/all_eg_gubbins.recombination_predictions.gff --out /mnt/eg/gubbins/220824_gubbins_aln.fasta

Any ideas what the issue might be?

Thanks in advance!

**Comment by nickjcroucher** [comment]
I think this is due to a Biopython upgrade - what version are you using?

**Comment by Dangoh** [comment]
Hi Nick,

Thanks for quick reply!

I've tried v1.76 and v1.78.

**Comment by nickjcroucher** [comment]
Just an FYI - Gubbins requires python version >=3.8 for parallelisation. Did you install with conda - and what happens if you use a more recent python version?

**Comment by Dangoh** [comment]
Solved! Tried later version of python and it works great!

**Comment by nickjcroucher** [comment]
Phew! Great, glad it's working now.

**Comment by sylarKYG** [comment]
> Solved! Tried later version of python and it works great!

Hi Dangoh,

What version of python and biopython did you use, same issue with you.
