### ISSUE TITLE
abnormal bases in recombinations

### ISSUE THREAD

**Issue by QianGuoPKU** [nickjcroucher/gubbins#351]
Hi Nicholas,

I got an average of 1,335,737 recombination bases within the 3,936,291 bp genome. I wonder if the average value is normal or too large. I have noticed that some research excluded genomes with proportions of recombination > 1.0%. Evidently, 1,335,737/3,936,291 (about 1/3) is larger than 1%. Do you have any idea about my issue? Maybe I need to choose another reference genome in the analysis?

Thanks,
Qian

**Comment by nickjcroucher** [comment]
That is a lot of recombination - these samples are probably too divergent to be analysed with Gubbins.
