### ISSUE TITLE
generate_ska_alignment.py problem (version 2)

### ISSUE THREAD

**Issue by mstagliamonte** [nickjcroucher/gubbins#352]
Hi, I have an issue similar to this: https://github.com/nickjcroucher/gubbins/issues/347 ; I am using gubbins/3.2.1

I have generated a tab-delimited file as suggested by @nickjcroucher in the above topic, with one column for fasta file name, and two columns for R1 and R2 files; however, in the resulting aligned fasta file, each sequence is represented twice (they are identical). I wonder if SKA does use the paired information, and this is just a glitch, or if it uses the two fastq files independently, and I should rather merge the R1 and R2 for added coverage.

Thank you,
Max

**Comment by nickjcroucher** [comment]
That's odd @mstagliamonte, just to check, your input file has the structure:
```
sequence_t1	./data/preprocessfasta/sequence_t1_1.fastq	./data/preprocessfasta/sequence_t1_2.fastq
sequence_t2	./data/preprocessfasta/sequence_t2_1.fastq	./data/preprocessfasta/sequence_t2_2.fastq 
sequence_t3	./data/preprocessfasta/sequence_t3_1.fastq	./data/preprocessfasta/sequence_t3_2.fastq
sequence_t4	./data/preprocessfasta/sequence_t4_1.fastq	./data/preprocessfasta/sequence_t4_2.fastq
```
And you're using a command like:
```
generate_ska_alignment.py --fastq fastq.list --reference sequence_t1.fasta --out test
````

**Comment by mstagliamonte** [comment]
Hi, @nickjcroucher ,

Thank your for kind answer. I am actually using both fasta and fastq files as input, as suggested by the manual here:  https://github.com/nickjcroucher/gubbins/blob/master/docs/gubbins_manual.md 

Here is my command line:

```
generate_ska_alignment.py --reference ../../refSeq_mb451/GCF_000176375.1_ASM17637v1_genomic.fna \
  --fasta list.fasta.ska --fastq list.fastq.ska --threads 4 --out test.ska.aln.fasta

```

Best,
Max

**Comment by nickjcroucher** [comment]
Are there different samples in each file? You would only need to use the FASTQ option if your data are unassembled.

**Comment by mstagliamonte** [comment]
> Are there different samples in each file? You would only need to use the FASTQ option if your data are unassembled.

The samples are the same. I did not realize I could just use the fastq files, as the manual mentioned the use of both fasta and fastq. I will try and use just fastq and check the results.

Best,
Max

**Comment by mstagliamonte** [comment]
**Update**: OK, I can confirm that when using either fasta or fastq as input, the output seems correct. Reading the manual page, I was under the impression that I had to use both fasta and fastq, while it seems that I should use only one kind of input. Please correct me if my conclusions are wrong.

Best,
Max

**Comment by nickjcroucher** [comment]
Just one type of input per isolate is required - I'll see if I can clarify this in the manual.

**Comment by mstagliamonte** [comment]
Great, Thank you. I appreciate you taking the time clarify my doubts.

Best,
Max
