### ISSUE TITLE
Illegal instruction (core dumped) Unable to fit model to data

### ISSUE THREAD

**Issue by DorothyTamYiLing** [nickjcroucher/gubbins#353]
Hi,

First of all, thanks for writing Gubbins such an amazing software.

I am trying to run Gubbins in a large dataset alignment (about 3000+ samples, each sample 4800K bp long). I have the following issues and there was also no log file produced. I managed to capture the following printings just before the error occurred: 

Gubbins command [Gubbins version v3.2.1]:
/home/ubuntu/miniconda3/envs/gubbins/bin/run_gubbins.py --prefix Sflex --starting-tree S-flex.snp-sites.fasta.treefile.mid2.tre mapping-S_flex_2a.masked_rename.aln --filter-percentage 35

#error message:
Using 1 distinct models/data partitions with joint branch length optimization

All free model parameters will be estimated by RAxML
GAMMA model of rate heterogeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 88664
Name: No Name Provided
DataType: DNA
Substitution Matrix: GTR

RAxML was called as follows:

raxmlHPC-AVX2 -p 7988 -safe -m GTRGAMMA -s mapping-S_flex_2a.masked_rename.aln.snp_sites.aln -n mapping-S_flex_2a.masked_rename.iteration_1_reconstruction -t /home/ubuntu/Dorothy/Shigella_dir/tmpiioyzz7v/mapping-S_flex_2a.masked_rename.iteration_1.tre.rooted -f e -w /home/ubuntu/Dorothy/Shigella_dir/tmpiioyzz7v

Illegal instruction (core dumped)
Unable to fit model to data

It would be great if I can know how to solve this problem. Also, because there was not any log file produced,  I tried to pipe the standard output of Gubbins into a file using the following command:
run_gubbins.py --prefix XX --starting_tree mytree.tre myfasta.fasta > gubbins.log
But for some reasons only some of the outputs can be captured using this method.

Many thanks,
Dorothy

**Comment by nickjcroucher** [comment]
It seems as though it is possibly running out of memory when fitting the phylogenetic model to the first alignment - you can try a simpler model for the first iteration (e.g. JC or GTR), a different model fitter (e.g. fasttree), and/or using more memory.

**Comment by DorothyTamYiLing** [comment]
Hi,

Thanks for the speedy reply, during the weekend! I will have a go and let you know if I have more issue.

Thanks and have a nice weekend.

Best wishes,
Dorothy
