### ISSUE TITLE
Very different trees using Gubbins and IQ-Tree

### ISSUE THREAD

**Issue by alanxelena** [nickjcroucher/gubbins#354]
Hi!

  I'm running (At least trying) an SNPs phylogenetic analysis. For this I did the following:
  
1) Snippy
2) Snippy-core
3) Snippy-clean
4) Gubbins
5) snp-sites on the gubbins filtered polymorphic sites
Since I don't get bootstrap values for the gubbins tree I used iq-tree on the output of snp-sites on gubbins as follows: iqtree -fconst 32781,37052,37202,32295 -b 1000

If I compare the nwk tree generated by gubbins and that from IQ-tree I get very different topologies. Is there an explanation for this? Am I doing something wrong?

Thanks a lot!

**Comment by nickjcroucher** [comment]
Gubbins runs on whole genome alignments, not SNP site alignments. You don't need steps 1-3, or step 5 - hopefully all is explained in https://github.com/nickjcroucher/gubbins/blob/master/docs/gubbins_manual.md.

**Comment by alanxelena** [comment]
Hi Nick!

  Thanks for the reply. I'm a little confused right now, there is documentation on using Gubbins after snippy and also pipelines that implement this approach:
  
https://github.com/nickjcroucher/gubbins/issues/210

https://gitlab.com/bfr_bioinformatics/snippySnake

https://hub.docker.com/r/sangerpathogens/gubbins

https://neatseq-flow.readthedocs.io/projects/neatseq-flow-modules/en/latest/Workflow_docs/Microbe-Flow.html

Maybe I'm understanding everything wrong, could you please clarify this for me?

Many thanks!

**Comment by nickjcroucher** [comment]
Apologies - it's been a busy few days - you are of course right, there's no problem using snippy to generate the alignment. But you don't need to run `snippy-core` you should use the whole genome alignment for Gubbins. I hope that helps, sorry for the confusion!

**Comment by alanxelena** [comment]
Dear Nick,

  No need to apologise and thanks for the reply. I have just one more question, in the Snippy docs, Torsten Seeman writes this:

> You can remove all the "weird" characters and replace them with N using the included snippy-clean_full_aln. This is useful when you need to pass it to a tree-building or recombination-removal tool:
 
`snippy-clean_full_aln core.full.aln > clean.full.aln`
`run_gubbins.py -p gubbins clean.full.aln`
`snp-sites -c gubbins.filtered_polymorphic_sites.fasta > clean.core.aln`
`FastTree -gtr -nt clean.core.aln > clean.core.tree`

Here's the link to the docs: https://github.com/tseemann/snippy

Here he's suggesting to run gubbins on clean.full.aln which comes from cleaning the file called core.full.aln (Everything that's core.* comes from a previous snippy-core run). My aim is to reduce the original alignment to the core alignment and run IQ-Tree on that. Which would be the correct approach? The one that Torsten suggests or running Gubbins on the clean version of snippy and then run snippy-core on the gubbins.filtered_polymorphic_sites.fasta?

Thanks a lot for your time and help!

**Comment by nickjcroucher** [comment]
Yes, sensible - I trust Torsten knows what he's talking about!
________________________________

**Comment by alanxelena** [comment]
Me too, but I also trust you! I'll follow Torsten's suggestion then but I still have no explanation regarding the different tree topologies. Sadly Torsten doesn't reply frequently to his github.

Thanks for all your replies!

**Comment by nickjcroucher** [comment]
If you run it without filtering for core SNPs that should help hopefully - makes a difference to how recombinations are detected
________________________________

**Comment by alanxelena** [comment]
Thanks,

   I'll give it a shot and see what happens. I'll link this discussion in Snippy's Github and see if I can get Torsten's opinion.
