### ISSUE TITLE
generate recombination prediction regions only

### ISSUE THREAD

**Issue by DorothyTamYiLing** [nickjcroucher/gubbins#355]
Hello,

I need to generate a phylogeny of a dataset of 3745 samples (each with 4988504bp) and correct for recombination. Due to my limited resources (8vCPU, 62G RAM) and to save time, plus there are some highly similar samples in my dataset, 
I made a new dataset after removing duplicated samples (1080 are removed) and I run Gubbins on them to detect regions of recombination. Then, based on the recombination predictions output I will mask those regions in the genomes (also for the 1080 duplicated genomes that were removed before accordingly). Then,  I will make an accurate phylogeny based on the 3745 masked genomes (maybe using iqtree).

Hence, I would only need the recombination prediction output from Gubbins but not the final tree. I am running Gubbins now as if I need the final tree, but I would like to use the .recombination_predictions.gff file as soon as it is ready. My question is how would I know when the generation of this file is complete? Is there a way to only ask Gubbins to generate recombination prediction regions?

This is the command that I am using:
run_gubbins.py --prefix Ssonnei --tree-builder iqtree --first-tree-builder fasttree --filter-percentage 35 --best-model --first-model GTRGAMMA --threads 7 /home/ubuntu/Dorothy/Shigella_project/mapping-S_sonnei_noplasmids.masked_dedup.aln

After about 3 hours of running, I had the following error message:

Running Gubbins to detect SNPs...
gubbins /home/ubuntu/Dorothy/Shigella_project/Ssonnei_gubbins/tmpyl8zgylk/mapping-S_sonnei_noplasmids.masked_dedup.aln
...done. Run time: 3039.71 s

Entering the main loop.

*** Iteration 1 ***

Constructing the phylogenetic tree with fasttree...
fasttree -nt -gtr -gamma -nosupport -out mapping-S_sonnei_noplasmids.masked_dedup.iteration_1.tre -log mapping-S_sonnei_noplasmids.masked_dedup.iteration_1.log /home/ubuntu/Dorothy/Shigella_project/Ssonnei_gubbins/mapping-S_sonnei_noplasmids.masked_dedup.aln.snp_sites.aln > /dev/null 2>&1
...done. Run time: 8036.27 s

Reconstructing ancestral sequences with pyjar...

Fitting substitution model to tree...
iqtree -nt 7 -safe -redo -m GTR+G4 -s mapping-S_sonnei_noplasmids.masked_dedup.aln.snp_sites.aln -t /home/ubuntu/Dorothy/Shigella_project/Ssonnei_gubbins/tmpyl8zgylk/mapping-S_sonnei_noplasmids.masked_dedup.iteration_1.tre.rooted --prefix /home/ubuntu/Dorothy/Shigella_project/Ssonnei_gubbins/tmpyl8zgylk/mapping-S_sonnei_noplasmids.masked_dedup.iteration_1  -n 0 --mlrate -redo
ERROR: Invalid "-safe" option.
Unable to fit model to data

It looks like that the 1st iteration had completed. However, in the output files there was not any *recombination prediction* files. Here are the list of output files generated:

mapping-S_sonnei_noplasmids.masked_dedup.aln.gaps.base_patterns.csv
mapping-S_sonnei_noplasmids.masked_dedup.aln.gaps.base_positions.csv
mapping-S_sonnei_noplasmids.masked_dedup.aln.gaps.phylip
mapping-S_sonnei_noplasmids.masked_dedup.aln.gaps.sequence_names.csv
mapping-S_sonnei_noplasmids.masked_dedup.aln.gaps.snp_sites.aln
mapping-S_sonnei_noplasmids.masked_dedup.aln.gaps.vcf
mapping-S_sonnei_noplasmids.masked_dedup.aln.phylip
mapping-S_sonnei_noplasmids.masked_dedup.aln.snp_sites.aln
mapping-S_sonnei_noplasmids.masked_dedup.aln.start
mapping-S_sonnei_noplasmids.masked_dedup.aln.vcf
mapping-S_sonnei_noplasmids.masked_dedup.iteration_1.tre

Thanks,
Dorothy

**Comment by nickjcroucher** [comment]
I tested this command on an alignment I know works with a fresh Gubbins install, and it completed successfully. What version of Gubbins and IQtree are you using?

With regard to your dataset, I would recommend just putting all the sequences into Gubbins, which will output an IQtree, I am not aware of any benefit of running IQtree independently on the masked alignment. If the memory resources are limiting, use `--mar` for the sequence reconstruction.

**Comment by DorothyTamYiLing** [comment]
Hi Nick,

Thanks for the reply. I will give the flag -mar a go and hopefully I can finish the Gubbins run with the full dataset. I am using iqtree 2.2.0 and Gubbins 3.2.1

Thanks,
Dorothy
