### ISSUE TITLE
Seems like gubbins failing to run on ~2500 whole genome alignemnt

### ISSUE THREAD

**Issue by UzmaBasit** [nickjcroucher/gubbins#356]
Hi @nickjcroucher, I am trying to run gubbins on one of the GBS lineages CC17) which is quite homogenous and has less recombination rate, but gubbins failed to generate even the first iteration tree after running for 28 to 30 days. I have had submitted my jobs with maximum no. of threads (n=32) to basement queue which runs the job for a month almost at Sanger, after that my gubbins job is failing due to reaching LSF memory limit. 
Would you please advise how to optimize gubbins run for such large no. of genomes. In future I will have to run gubbins on more diverse lineages as well comprising of around same no. of genomes (~2500).
Thanks

**Comment by nickjcroucher** [comment]
What command did you use?

**Comment by UzmaBasit** [comment]
run_gubbins.py --threads 32 core.full.aln
For this job I am using snippy core output as input to gubbins.
Before I was using whole genome alignemnt file from smalt (alignment tool) as the input.

**Comment by nickjcroucher** [comment]
You should use the whole genome alignment.

Try `run_gubbins.py --frst-tree-builder rapidnj --first-model JC --threads 32 core.full.aln`, and if that doesn't work, `run_gubbins.py --frst-tree-builder rapidnj --first-model JC --mar --threads 32 core.full.aln`.

**Comment by nickjcroucher** [comment]
You can also provide the species-wide PopPUNK tree as a starting tree, as long as it contains all the sequences with correctly-formatted names.

**Comment by UzmaBasit** [comment]
Many thanks Nick for your prompt reply. I am giving it a try now and will update you how it goes.

**Comment by nickjcroucher** [comment]
I assume this worked?

**Comment by UzmaBasit** [comment]
Hi Nick, Yes this has worked very well and the job finished successfully in less than 10 days. Many thanks for your help!

**Comment by qianxin-kxy** [comment]
> Hi Nick, Yes this has worked very well and the job finished successfully in less than 10 days. Many thanks for your help!

Hello Uzma, I have also encountered the same issues. Can you tell me which of Nick's three solutions you used to complete the analysis
1.run_gubbins.py --frst-tree-builder rapidnj --first-model JC --threads 32 core.full.aln
2.run_gubbins.py --frst-tree-builder rapidnj --first-model JC --mar --threads 32 core.full.aln
3.provide the species-wide PopPUNK tree as a starting tree, as long as it contains all the sequences with correctly-formatted names

Besides, I don't understand what this sentence means? “the species-wide PopPUNK tree as a starting tree”。 I don't know if this understanding is correct? For example, Newick generated by raxml can be used as the input file

**Comment by qianxin-kxy** [comment]
> I assume this worked?

Hi Nick，I have also encountered this issue, using the following code to analyze over 900 strains. It has been several days, but it is still not completed. May I directly use the code you provided to Uzma for execution, or do I need any additional code?

(gubbins) [kxy@zju snippy] nohup run_gubbins.py -p gubbins clean.full.aln &

Reference：https://github.com/tseemann/snippy

**Comment by nickjcroucher** [comment]
Try using `--first-tree-builder rapidnj --first-model JC` as options to speed up the initial tree building. Also make sure you have divided your population up into strains first, to increase the accuracy of the algorithm, and limit the diversity within the analysis.

**Comment by qianxin-kxy** [comment]
> Try using `--first-tree-builder rapidnj --first-model JC` as options to speed up the initial tree building. Also make sure you have divided your population up into strains first, to increase the accuracy of the algorithm, and limit the diversity within the analysis.

Thank you for your prompt reply. I will try using the following code
$ nohup run_gubbins.py --first-tree-builder rapidnj --first-model JC --threads 100 -p gubbins /data/users/kxy/kxytry/assembleddata/analysis/snippy/clean.full.aln &
