### ISSUE TITLE
Multiple outgroups may inflate execution time

### ISSUE THREAD

**Issue by stitam** [nickjcroucher/gubbins#357]
Hi, at this point this is more a question than an issue..

I would like to build a tree in which I set multiple outgroups. My outgroups are from a diverse set of taxa, some not even in the same genus as the lineage for which I would like to build the tree (which I am building for a sequence type within a species). I use one of the non-outgroup strains as reference to construct pseudo-whole genomes with snippy, and then use the longest contigs to build the tree with gubbins. I noticed that the execution time was heavily inflated compared to a run with no outgroups specified, it took multiple hours when it should have completed in about 30 minutes. I am trying to figure out what is causing this behaviour. So far I have these guesses:

* While the outgroups in my analysis do not mix with any of the tips, they do however form multiple clades
* One or more of the outgroup strains in my analysis are too distant from the lineage I want to build the tree for

Any ideas what may be causing this problem? Many thanks.

**Comment by nickjcroucher** [comment]
Using very divergent outgroups will greatly increase run time because of the computation needed to reconstruct the patterns of base substitutions across many polymorphic sites. I would strongly recommend using a single, closely-related outgroup.

**Comment by stitam** [comment]
Many thanks @nickjcroucher for your help, this is a super important detail. I'll go ahead as you suggested.
