### ISSUE TITLE
Gubbins using the WGS alignment created using contigs

### ISSUE THREAD

**Issue by snackens** [nickjcroucher/gubbins#358]
Hi, thank you for this great tools.

I'd like to detect recombination regions using gubbins.
I'm going to use Snippy to create whole genome sequence alignment file for gubbins.

% snippy-clean_full_aln core.full.aln > clean.full.aln
% run_gubbins.py -p gubbins clean.full.aln

One concern is that my dataset includes both complete geneome and contig level genome(90 % of my dataset are contig level). Finally I'd like to construct phylogenetic tree.
In this case, are there any problems  regarding using a lot of contig level genomes?

Best regards,

**Comment by nickjcroucher** [comment]
I would exclude poor quality draft assemblies that are likely to be contaminated/generated from low coverage data, but otherwise we have not encountered problems with this approach (e.g. [here](https://genomemedicine.biomedcentral.com/articles/10.1186/s13073-022-01147-2)).
