### ISSUE TITLE
Ignore excluding sequence which has missing data

### ISSUE THREAD

**Issue by snackens** [nickjcroucher/gubbins#359]
Hi, I'd like to get whole genome alignment after removing recombinant regions.
But while gubbins, one strain is excluded because of a lot of missing data as following.

Excluded sequence XXX because it had 27.37969901914598 percentage missing data while a maximum of 25.0 is allowed

Are there any options which allow to ignore the above?
Or Do you recommend to change the reference sequence in Snippy?
Thanks,

**Comment by nickjcroucher** [comment]
--filter-percentage FILTER_PERCENTAGE, -f FILTER_PERCENTAGE
                        Filter out taxa with more than this percentage of gaps (default: 25.0)

But probably a good idea to exclude this sequence unless it's an outgroup or very important.
