### ISSUE TITLE
Error: Bipartitions missing when harmonising roots between trees

### ISSUE THREAD

**Issue by eam12** [nickjcroucher/gubbins#360]
I've been using Gubbins for years and am a huge fan. Thank you for developing this program. Today I encountered an error I've never received before:

```
Bipartitions missing when harmonising roots between trees gubbins/tmplua1dxdq/coreFiltered_clean.full.1675353838.iteration_1.treefile and gubbins/tmplua1dxdq/coreFiltered_clean.full.1675353838.iteration_1.tre.rooted
The missing bipartitions are: ['00000000000000000000000000000000000000000000000000000000000000001100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000']
```

I took a peek at the source code and apparently this is something that can happen when using FastTree to fit a phylogenetic model, but I'm using IQ-Tree:

```
run_gubbins.py --prefix gubbins --tree-builder iqtree --threads 12 --use-time-stamp coreFiltered_clean.full.aln
```

Any clue as to what's going on? Thanks so much!

**Comment by nickjcroucher** [comment]
Hmm, interesting - what version are you using?

**Comment by eam12** [comment]
I've encountered the same error with both versions 3.1.6 and 3.3.

**Comment by nickjcroucher** [comment]
The issue can arise if there is a multifurcation in the trees - can you share the two files that are referred to in the error?

________________________________

**Comment by eam12** [comment]
What's the best way to send them to you? They do contain some unpublished data so I would prefer to send them to you privately, if possible.

**Comment by nickjcroucher** [comment]
Of course - you can [email](mailto:n.croucher@imperial.ac.uk) me

**Comment by nickjcroucher** [comment]
There are two taxa on ~zero length branches that are differently positioned on the two trees - this occurs after the model fitting, which should be using IQtree. Could you try using `--model-fitter raxml` and check whether that fixes the issue?

**Comment by noemielefrancq** [comment]
Hello all, 

I've ran into the same error. I'm working on a large tree with some very small branch lengths. I was using iqtree as the tree builder and the model fitter. Gubbins version 3.3.0, iqtree v2.2.3.

I can confirm changing the model fitter to raxml (--model-fitter raxml) fixed the issue!

Best, Noemie
