### ISSUE TITLE
Iteration1: Failed while building the tree with snippy-clean.aln

### ISSUE THREAD

**Issue by rajneeshdadwal** [nickjcroucher/gubbins#362]
hey 
I was using gubbins after snippy-clean_full_aln core.full.aln > clean.full.aln on clean.full.aln and got the following error:

Entering the main loop.

*** Iteration 1 ***

Constructing the phylogenetic tree with raxmlHPC-AVX2...
raxmlHPC-AVX2 -p 2187 -safe -m GTRGAMMA -f d -p 1 -s /home/rajneesh/test/snippy/clean.full.aln.phylip -n clean.full.iteration_1 > /dev/null 2>&1
Failed while building the tree.

anything that can be done

**Comment by nickjcroucher** [comment]
Are you able to generate a tree from this alignment using other phylogenetic software (e.g. rapidnj)?

**Comment by rajneeshdadwal** [comment]
i have made it using raxml only using the following command:

raxmlHPC-PTHREADS  -T 8 -m GTRGAMMA -s core.aln -n tree.nwk

**Comment by nickjcroucher** [comment]
What version of Gubbins are you using? Does the tree building command work as `raxmlHPC-AVX2 -T 8 -m GTRGAMMA -s core.aln -n tree.nwk`?

**Comment by rajneeshdadwal** [comment]
it doesn't works with the command:

raxmlHPC-AVX2 -T 8 -m GTRGAMMA -s core.aln -n tree.nwk

**Comment by nickjcroucher** [comment]
What version of Gubbins are you using?

**Comment by rajneeshdadwal** [comment]
The version 3.2.1.

**Comment by nickjcroucher** [comment]
It's using the wrong version of RAxML for your CPU - would you be able to run `sysctl -a | grep machdep.cpu.features` if you are using a Mac, or `grep flags /proc/cpuinfo` if you are using a Linux machine?

Solutions I would recommend:
(1) Upgrade to Gubbins v3.3
(2) If it is still not working, use IQtree instead as your tree builder

**Comment by rajneeshdadwal** [comment]
I am using gubbins under my WSL environment maybe that is causing the problem..
I have proceeded with IQtree for my data as of now.

**Comment by nickjcroucher** [comment]
Glad that's working, thanks for the update

**Comment by xxxxxxsf** [comment]
I met the same problem with you. byut when runing "raxmlHPC-AVX2 XXXXXXX", it tell me "too few". Then  I added 4 snippy output files after "snippy-core" command, and it worked
