### ISSUE TITLE
Running error of "core dumped"

### ISSUE THREAD

**Issue by aslangabriel99** [nickjcroucher/gubbins#366]
Hi, I ran the command "run_gubbins.py -p /home/work/CPSNP --threads 12 /home/work/CPSNP.aln" on linux server with editon 3.0.0, and my ram is 125.8G. However it stuck at the step of "Running joint ancestral reconstruction with pyjar" . The screencapture was attached as follows:
<img width="618" alt="1" src="https://user-images.githubusercontent.com/56073902/235468042-e3abff3a-3584-4202-8723-f0ba6f605455.png">

**Comment by nickjcroucher** [comment]
Can you try the latest version? Anything >=3.2 should run the reconstruction more efficiently.
