### ISSUE TITLE
Bipartitions missing when transferring node label

### ISSUE THREAD

**Issue by mesti90** [nickjcroucher/gubbins#369]
I have an error on some datasets when running gubbins 3.2.1.
The software was called with the following command:
`run_gubbins.py     --tree-builder fasttree     --threads 30     --iterations 100    --extensive-search     chromosomes.fasta`

The error message:
`Bipartitions missing when transferring node label transfer: ['00000000000000000011....']`

**Comment by nickjcroucher** [comment]
Thanks - can you please try upgrading to v3.3 and testing whether the issue reappears? Otherwise it may be worth changing the tree building or model fitting algorithm (e.g. to RAxML). Also `--iterations 5` should be plenty, otherwise the run will take a long time!

**Comment by mesti90** [comment]
Version 3.3 does not solve the issue: it still ends with the same error, except for a warning: `This is a known issue when using FastTree to fit a phylogenetic model; use an alternative algorithm`
What can be the reason of this error? How to solve it if I'd like to use FastTree?

**Comment by nickjcroucher** [comment]
Fasttree cannot be used to fit a model when there are zero length branches. You can still build the tree with Fasttree, but you will need to specify a different algorithm with `--model-fitter`, e.g. RAxML.

________________________________
