### ISSUE TITLE
what are the best parameters that can be use for identical sequences in Raxml?

### ISSUE THREAD

**Issue by SachiiM** [nickjcroucher/gubbins#373]
I have a set of 22 sequences that are identical, except for one sequences which differ in 2 bp compared to the rest.  Although the sequences are identical I still require to generate a ML tree for these sequences.

I ran the RXML tree with Rapid bootstrap GTR GAMMA to generate a tree. However instead of obtaining polytomy, I'm observing a clade separation for the identical sequences which is not accurate.  Can someone help me how to deal with this?

Thank you

**Comment by nickjcroucher** [comment]
This is not a Gubbins-related issue.
