### ISSUE TITLE
Dockerfile for gubbins

### ISSUE THREAD

**Issue by stitam** [nickjcroucher/gubbins#374]
Hi, I recently encountered an error and after some browsing concluded that I should change the model fitter from `raxml` to `raxmlng`. Unfortunately the docker in which I run gubbins is now missing some packages so now I have to figure out how to update the container. 

This is fine for now, but I was wondering: do you think it would be possible to add a Dockerfile to this repo (possibly starting from a debian or ubuntu base image) which we can always use to build a fully operational gubbins container? Many thanks.

**Comment by nickjcroucher** [comment]
There used to be one, but this was discontinued after Docker started charging. If we get any resources for maintaining/developing Gubbins, then we'll look to get one up and running again.
