### ISSUE TITLE
Muliple sequence alignment as input

### ISSUE THREAD

**Issue by tbazilegith** [nickjcroucher/gubbins#375]
Hi Nick,
Does gubbins take multiple sequence alignment as input?
I have fasta files for several strains of a species - wonder if I can align those fasta sequences
Thanks,
TJ

**Comment by nickjcroucher** [comment]
Yes - please see the [tutorial](https://github.com/nickjcroucher/gubbins/blob/master/docs/gubbins_tutorial.md). You should check your isolates are closely related using software such as [PopPUNK](https://github.com/bacpop/PopPUNK).
