### ISSUE TITLE
identifying the donor of recombination events

### ISSUE THREAD

**Issue by evolbeginner** [nickjcroucher/gubbins#377]
I have a question regarding the identification of the direction of recombination events. While I realize that gubbins may not tell the direction of a recombination event (indicated in the _recombination_predictions.gff_ file), I was wondering if it is possible to tell the donor by the following strategy. Use the reconstructed sequence at the node of interest (denoted as _node_a_) to search against the sequences of all other nodes, tips included. If it maps well to the sequence of another ancestral node (denoted as _node_i_), then does it provide evidence that the recombination is from _node_i_ to _node_a_? The strategy may sound naïve but I was just wondering if it makes sense. Thanks!

**Comment by nickjcroucher** [comment]
Gubbins effectively asssumes that the donor of the recombination is outside the tree, i.e. your analysed dataset should only consist of closely-related isolates (e.g. a strain defined by [PopPUNK](https://github.com/bacpop/PopPUNK)). So looking for the donor within the tree is not expected to be effective. [This](https://elifesciences.org/articles/67113) is an example of a post-Gubbins analysis where we have searched for the donor of recombinations in a post hoc analysis, using a diverse database of possible donors - that is what I would recommend.
