### ISSUE TITLE
IQtree executable name for IQtree 2.x is iqtree2

### ISSUE THREAD

**Issue by tillea** [nickjcroucher/gubbins#379]
Hi,
when packaging gubbins 3.3.0 for Debian and running its test suite I realised that gubbins can't find the iqtree executable.  While I tried to rename this inside the gubbins code in a [patch](https://salsa.debian.org/med-team/gubbins/-/blob/master/debian/patches/iqtree2.patch) there might be some other instances of a reference to /usr/bin/iqtree while IQtree upstream decided to name the executable `iqtree2`.   Before I keep on patching I'd like to report this issue to you for further discussion.
Kind regards, Andreas.

**Comment by nickjcroucher** [comment]
Thanks for highlighting @tillea - I think your link is broken though :)

**Comment by tillea** [comment]
> Thanks for highlighting @tillea - I think your link is broken though :)

Argh, fixed.  Sorry for that broken advertising (despite that chocolate festival is nice ;-) )

**Comment by tillea** [comment]
BTW, the patch above is sufficient.  First I assumed that there would be more patching needed.  However, it was just me who failed to add iqtree to the dependencies of the CI test.

**Comment by nickjcroucher** [comment]
Are there any further issues that need addressing?

**Comment by tillea** [comment]
Am Wed, Jul 26, 2023 at 06:26:50AM -0700 schrieb nickjcroucher:
> Are there any further issues that need addressing?
Not that I'm aware off.
Kind regards, Andreas.

**Comment by nickjcroucher** [comment]
Great, thanks for letting me know!

**Comment by alanorth** [comment]
What was the resolution here? I'm building gubbins v3.4.0 on our HPC cluster (no conda) and it fails looking for `iqtree`. In iqtree v2.2.0 and v2.4.0 at least, the binary is called `iqtree2`.

For now I will patch gubbins locally:

```diff
diff --git a/python/gubbins/treebuilders.py b/python/gubbins/treebuilders.py
index 203ade8..2dab3e0 100644
--- a/python/gubbins/treebuilders.py
+++ b/python/gubbins/treebuilders.py
@@ -278,7 +278,7 @@ class IQTree:
         self.additional_args = additional_args

         # Construct base command
-        self.executable = "iqtree"
+        self.executable = "iqtree2"
         if utils.which(self.executable) is None:
             sys.exit("No usable version of IQTree could be found.")
         command = [self.executable]
```

Maybe I should submit the patch here?
