### ISSUE TITLE
alignment to use in final tree

### ISSUE THREAD

**Issue by tbazilegith** [nickjcroucher/gubbins#380]
Hi Nick,
I am a little uncertain about which alignment( masked aln or the original one) to use in the command below
generate_files_for_clade_analysis.py --list isolates_list.txt <<--aln in.aln>> --gff ../*recombination_predictions.gff --tree *.final_tree.tre

Thanks,
TJ

**Comment by nickjcroucher** [comment]
It uses the original input alignment, the script will mask the recombinations itself.

**Comment by tbazilegith** [comment]
Thanks!
________________________________
