### ISSUE TITLE
alignment in final tree

### ISSUE THREAD

**Issue by tbazilegith** [nickjcroucher/gubbins#381]
Hi Nick,
I am a little bit uncertain about which alignment (masked alignment or the original one) to use in the command below. The manual doesn't specify... Any ideas?
generate_files_for_clade_analysis.py --list isolates_list.txt --aln **in.aln** --gff *.recombination_predictions.gff --tree *.final_tree.tre

Thanks,
TJ

**Comment by nickjcroucher** [comment]
See #380.
