### ISSUE TITLE
mask_gubbins_aln.py not removing recombinant regions

### ISSUE THREAD

**Issue by erinpnewcomer** [nickjcroucher/gubbins#385]
Hi! 

I'm trying to create a masked core genome alignment so I can see what % of the core is getting masked by Gubbins, but the script mask_gubbins_aln.py doesn't seem to be making any changes to the input core.aln. The recombination_predictions.gff file has 1501 lines of predictions. Has anyone else encountered this/any ideas on how to fix this?

**Comment by nickjcroucher** [comment]
Are there any unusual characters in your isolate names (e.g. "#"?)

**Comment by sylarKYG** [comment]
> Are there any unusual characters in your isolate names (e.g. "#"?)

Same issue with Erin.
The mask aln is as same large as input aln.
The isolate name has "." and "_".

**Comment by nickjcroucher** [comment]
What version are you using, and what is the command you are running?

**Comment by sylarKYG** [comment]
Python: 3.11.7 Biopython: 1.82
The command: python3.11 /data4/CLC_data4/shiqiucheng/software/mask_gubbins_aln.py --aln clean.full.aln --gff clean.full.recombination_predictions.gff --out clean.full.mask.aln
recombination_predictions.gff file has 1457 lines of predictions.

**Comment by nickjcroucher** [comment]
Thanks - what version of Gubbins?

**Comment by sylarKYG** [comment]
gubbins 2.4.1

**Comment by nickjcroucher** [comment]
Try upgrading to the latest version (3.3.2)

**Comment by sylarKYG** [comment]
How does the recombination removal fragment show in the alignment file, replace by "_" or "N"? 
Because byte count of clean.full.aln and clean.mask.aln are identical, but the counts of ATCG are different.

**Comment by nickjcroucher** [comment]
Whatever you set the [missing character](https://github.com/nickjcroucher/gubbins/blob/master/python/scripts/mask_gubbins_aln.py) to - by default it is `-` - this is documented in the script's help.
