### ISSUE TITLE
how long does joint ancestral reconstruction with pyjar take?

### ISSUE THREAD

**Issue by lagphase** [nickjcroucher/gubbins#386]
Hello,

I have 206 sequences whose whole genome alignment is about 653 Mb. The run has been staying at joint ancestral reconstruction step for a day now. I'm wondering whether it is stalled or how long this step usually takes. My code is

`run_gubbins.py --first-tree-builder rapidnj --first-model JC --threads 144 -p gubbins clean.full.aln`

Thank you.

**Comment by nickjcroucher** [comment]
It will depend on the number of polymorphic sites - this is the slowest part of the algorithm - did it complete?
