### ISSUE TITLE
Possibility to fix the seed - for testing purpose of reproducibility ? (enhancement)

### ISSUE THREAD

**Issue by evezeyl** [nickjcroucher/gubbins#388]
Hi,
Would it be possible to provide an option to fix the seed for testing purposes, for reproducibility (that can be provided in run_gubbins.py). I see that there is seed options that could be modified/accessed in treebuilders.py ...  but not directly accessible in the launcher.

All the best
Eve

**Comment by nickjcroucher** [comment]
Good idea - I will add this when I get a chance next.

**Comment by nickjcroucher** [comment]
Added in [89a1e55](https://github.com/nickjcroucher/gubbins/commit/89a1e552c14420402782c468f025732c1c220dd7).
