### ISSUE TITLE
Gubbins input file error

### ISSUE THREAD

**Issue by marianajeeb** [nickjcroucher/gubbins#393]
Hello,

I tried to install Gubbins in Conda environment, but failed to do using every command. Later, I installed it from the source code. I have created input alignment using "ska". However, when trying to run with Gubbins.py command its giving input file error. Could you please help, how do you generate your input file?

Thanks

**Comment by nickjcroucher** [comment]
Please see https://github.com/nickjcroucher/gubbins/blob/master/docs/gubbins_tutorial.md.
