### ISSUE TITLE
File names with spaces cause error

### ISSUE THREAD

**Issue by johnlees** [nickjcroucher/gubbins#394]
Crass to have a space in paths I know, but technically permitted since Windows 95 I believe:
```
Running Gubbins to detect SNPs...
gubbins /Users/jlees/Documents/EBI/SKA project/pmen1/tmpxt6aiqem/pmen1.aln
Error: File '/Users/jlees/Documents/EBI/SKA' does not exist
```
With gubbins 3.3.1

Need to add quotes in the subcommand I guess?

**Comment by johnlees** [comment]
I think change https://github.com/nickjcroucher/gubbins/blob/master/python/gubbins/common.py#L227
```
gubbins_command = " ".join([gubbins_exec, input_args.alignment_filename])
```
to
```
gubbins_command = f"{gubbins_exec} \"{input_args.alignment_filename}\""
```

**Comment by nickjcroucher** [comment]
Thank you! Incorporated in #397.
