### ISSUE TITLE
Conda Gubbins 3.3.3 : Not able to install

### ISSUE THREAD

**Issue by ajkarloss** [nickjcroucher/gubbins#395]
Thanks a lot for the coda env for 3.3.3. 

conda install bioconda::gubbins does not work. Its hanging there for hours and nothing happens. Older versions are good and able to install.

**Comment by nickjcroucher** [comment]
This seems to be due to `numba` not being compatible with python >3.10, fixed attempted in #397.

**Comment by nickjcroucher** [comment]
Should now be fixed in v3.3.4.

**Comment by ajkarloss** [comment]
Thanks a lot
