### ISSUE TITLE
Conda Gubbins 3.3.4 : Not able to install

### ISSUE THREAD

**Issue by ajkarloss** [nickjcroucher/gubbins#398]
H, Thanks a lot for the updates. But not able to install the 3.3.4 through conda. We tried in CentOS and Mac. Both are just hanging there.

**Comment by nickjcroucher** [comment]
Can you install from source?

**Comment by ajkarloss** [comment]
I dont have sudo access to install it in our VM/server.

**Comment by nickjcroucher** [comment]
Please try to install v3.3.5, released on `conda` today.

**Comment by ajkarloss** [comment]
The problem still persists: In mac, it installed 2.3.4 in MacOS and "trying to Install" in CentOS for hours.

**Comment by nickjcroucher** [comment]
What are the commands you are using?

**Comment by ajkarloss** [comment]
conda install bioconda::gubbins

**Comment by ajkarloss** [comment]
https://anaconda.org/bioconda/gubbins

**Comment by nickjcroucher** [comment]
What about a fresh env? `mamba create -c bioconda -n gubbins_env gubbins python=3.9`

**Comment by ajkarloss** [comment]
I will try and update you

**Comment by ajkarloss** [comment]
Yes, it works with Mamba in my mac. But I need to install in a production server where I dont have permission to Install mamba. I need to send a request to Admins to install and they may take time to check/test/install.  Is there anyway to fix to install using normal conda? Thanks a lot. Gubbins is one of the most used tool in our workplace. Thanks a lot for the tool

**Comment by nickjcroucher** [comment]
Should work with `conda` as well, it will just be slower. Good luck!
