### ISSUE TITLE
Unable to install gubbin 

### ISSUE THREAD

**Issue by dzc0104** [nickjcroucher/gubbins#399]
Hi, 

I was trying to install Gubbins through the Recommended installation method - conda and OSX/Linux - installing from the repository in my local terminal. I had downloaded and installed anaconda3. 

The error that I am getting is the package for gubbin is not found.

I have attached hereby the word file which contains what I did. Please find the attachment.
[Gubbin install troubleshoot.docx](https://github.com/nickjcroucher/gubbins/files/14630949/Gubbin.install.troubleshoot.docx)

**Comment by nickjcroucher** [comment]
I would try replacing `conda` with `mamba` - that should solve the environment, although there do appear to be problems installing the latest version, as identified by other issues.

**Comment by dzc0104** [comment]
Thanks for the response @nickjcroucher, I tried with mamba using the command line

1)conda install -n base -c conda-forge mamba
2)mamba create -n myenv python=3.8
3) mamba activate myenv
4)mamba init : (error: package not found and permission denied)
5)mamba install gubbin (following package could not be installed)

6)sudo mamba init
7)mamba install -c conda-forge -c bioconda gubbin (package could not be installed)

8)mamba activate base. Run 'mamba init' to be able to run mamba activate/deactivate
and start a new shell session. Or use conda to activate/deactivate (error: package not found)

I'm still facing problems. Am I missing something here to troubleshoot it?

**Comment by nickjcroucher** [comment]
Does `mamba install gubbins` work?

**Comment by dzc0104** [comment]
It said the following package could not be installed.
@nickjcroucher

**Comment by nickjcroucher** [comment]
Please try to install v3.3.5, released on `conda` today.

**Comment by nickjcroucher** [comment]
Please reopen if there is still a problem.
