### ISSUE TITLE
Multithreading not working on v3.3

### ISSUE THREAD

**Issue by Alejandro-PI** [nickjcroucher/gubbins#400]
Hi! 
I want to use Gubbins on 11k genomes. I'm using version 3.3 as more recent versions couldn't be installed. However I notices that multithreading was not working despite using the --threads 6 option. Is it a issue of the version?

**Comment by nickjcroucher** [comment]
Not every step of the algorithm is yet multithreaded - e.g. recombination detection - but most of the algorithm should be parallelised.
