### ISSUE TITLE
Can Gubbins be used on eukaryotic genomes?

### ISSUE THREAD

**Issue by Adamtaranto** [nickjcroucher/gubbins#401]
Can Gubbins be used on sexually recombining haploid fungal genomes? The reference genome will have multiple chromosomes.

**Comment by nickjcroucher** [comment]
Yep - it's imperfect, because recombinations can be falsely inferred to go over the edge of chromosome boundary, but we have applied it previously to such genomes and it can do a good job (depending on the sampling of the collection and biology of the species).
