### ISSUE TITLE
Does Gubbins can be used for Mycobacterium tuberculosis?

### ISSUE THREAD

**Issue by TaoCheng98** [nickjcroucher/gubbins#407]
Hi Dr. Nicholas Croucher,

I have a question to consult you about the use of Gubbins.

In a recent article I submitted, a reviewer questioned the appropriateness of using Gubbins to construct a phylogenetic tree in Mycobacterium tuberculosis, a bacterium with low recombination rates. I would like to ask your opinion on whether Gubbins can be used for phylogenetic tree construction in Mycobacterium tuberculosis without encountering errors at least.

As the author of Gubbins, I would like to know, from your perspective, if Gubbins can be used for Mycobacterium tuberculosis?
#
2. The authors have used Gubbins, which does not work with core SNP alignment. The rationale of using it is unclear as recombination in M. tuberculosis is a rare event and its population structure is considered to be strictly clonal.
#

Thanks！

Tao

**Comment by nickjcroucher** [comment]
Gubbins should still accurately infer a tree when applied to _M. tuberculosis_. It may identify clusters of SNPs as recombinations in the PE-PPE repeats, depending on your mapping approach. This could increase the accuracy of the tree. It could also identify false positive recombinations from SNPs that are close together by chance. This could reduce the resolution of your tree. It would be unlikely to infer substantial levels of recombination, or dramatically change the shape of the inferred tree relative to other phylogenetic software.

Also, it is important to emphasise the reviewer is correct that Gubbins cannot be used on an alignment of polymorphic sites.

**Comment by TaoCheng98** [comment]
Hi Dr. Nicholas Croucher,

Torsten Seemann mentioned in snippy "https://github.com/tseemann/snippy" that if we want to build a Core SNP phylogeny, he will include gubbins as one step in the process. How do you view this issue?

##
% snippy-clean_full_aln core.full.aln > clean.full.aln
% run_gubbins.py -p gubbins clean.full.aln
% snp-sites -c gubbins.filtered_polymorphic_sites.fasta > clean.core.aln
% FastTree -gtr -nt clean.core.aln > clean.core.tree
##


best wish!
 Tao

**Comment by nickjcroucher** [comment]
As long as it is a whole genome alignment, not an alignment of only polymorphic sites, that is fine.

**Comment by TaoCheng98** [comment]
It seems like the reviewer misunderstood my intention. My input for Gubbins alignment is based on snippy's core genome rather than core SNP alignment.

**Comment by nickjcroucher** [comment]
Good to know - I just want to make that point clear for anyone else who finds this exchange! Best of luck with the resubmission.
