### ISSUE TITLE
raxmlHPC-AVX2 error

### ISSUE THREAD

**Issue by douco-ai** [nickjcroucher/gubbins#410]
Hi Nick
I'm using Gubbins v3.3.5 as indicated below:
run_gubbins.py -p gubbins coresnps.full.aln
After the first iteration during model fitting gubbins breaks with the following error:
--- Gubbins 3.3.5 ---

Croucher N. J., Page A. J., Connor T. R., Delaney A. J., Keane J. A., Bentley S. D., Parkhill J., Harris S.R. "Rapid phylogenetic analysis of large samples of recombinant bacterial whole genome sequences using Gubbins". Nucleic Acids Res. 2015 Feb 18;43(3):e15. doi: 10.1093/nar/gku1196.

Checking dependencies and input files...

Checking input alignment file...

Filtering input alignment...
...done. Run time: 29.43 s

Running Gubbins to detect SNPs...
gubbins "/home/chenfei/cfsm/cfdata/snippy_sm/tmpxo4l0t7r/coresnps.full.aln"
...done. Run time: 49.54 s

Entering the main loop.

*** Iteration 1 ***

Constructing the phylogenetic tree with raxmlHPC-AVX2...
raxmlHPC-AVX2 -safe -m GTRGAMMA -p 6737 -f d -p 1 -s /home/chenfei/cfsm/cfdata/snippy_sm/coresnps.full.aln.phylip -n coresnps.full.iteration_1 > /dev/null 2>&1
Failed while building the tree.

Any help would be much appreciated.

**Comment by nickjcroucher** [comment]
Would you be able to share the output of `grep flags /proc/cpuinfo` (on a Mac) or `sysctl -a | grep machdep.cpu.features` (on Linux)? Hopefully the analysis will work if you run `--tree-builder iqtree`.

**Comment by douco-ai** [comment]
run "grep flags /proc/cpuinfo" ,Obtain the following results:
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d

run --tree-builder iqtree ,After the following code appeared, there was no progress after waiting for about an hour.
run_gubbins.py --tree-builder iqtree coresnps.aln

--- Gubbins 3.3.5 ---

Croucher N. J., Page A. J., Connor T. R., Delaney A. J., Keane J. A., Bentley S. D., Parkhill J., Harris S.R. "Rapid phylogenetic analysis of large samples of recombinant bacterial whole genome sequences using Gubbins". Nucleic Acids Res. 2015 Feb 18;43(3):e15. doi: 10.1093/nar/gku1196.

Checking dependencies and input files...

Checking input alignment file...

Filtering input alignment...
...done. Run time: 0.68 s

Running Gubbins to detect SNPs...
gubbins "/home/chenfei/cfsm/cfdata/snippy_sm/tmpj13snjos/coresnps.aln"
...done. Run time: 2.51 s

Entering the main loop.

*** Iteration 1 ***

Constructing the phylogenetic tree with iqtree...
iqtree -nt 1 -safe -redo -m GTR+G4 -seed 1960 -s /home/chenfei/cfsm/cfdata/snippy_sm/coresnps.aln.phylip -pre coresnps.iteration_1 -quiet

**Comment by nickjcroucher** [comment]
This is a bug in the selection of the raxml executable (it is using raxmlHPC-AVX2 when your CPU only supports AVX) - I will need to fix this. In the mean time, IQTREE2 should work, but it will be slow - to speed up the analysis you can use `--first-tree-builder fasttree` or `--first-tree-builder rapidnj`.

**Comment by nickjcroucher** [comment]
Should be fixed by 13f1e64.
