### ISSUE TITLE
Problem to install on MacBook osx-amr64

### ISSUE THREAD

**Issue by Fla1487** [nickjcroucher/gubbins#420]
As describe I have a problem to install the package:

XXXXXX~ % conda install -c conda-forge -c bioconda -c defaults snippy
Channels:
 - conda-forge
 - bioconda
 - defaults
 - r
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides emboss >=6.0 needed by snippy-4.4.0-0

Could not solve for environment specs
The following packages are incompatible
└─ snippy is not installable because there are no viable options
   ├─ snippy [4.4.0|4.4.1|4.4.3|4.4.5] would require
   │  └─ emboss >=6.0 , which does not exist (perhaps a missing channel);
   ├─ snippy 4.4.5 would require
   │  └─ bcftools >=1.9,<1.10 , which does not exist (perhaps a missing channel);
   └─ snippy [4.5.0|4.5.1|4.6.0] would require
      └─ freebayes >=1.3.1 , which does not exist (perhaps a missing channel).

do you have any suggestions?
Thank you in advance

**Comment by nickjcroucher** [comment]
You will need to contact the snippy maintainers.
