### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by antunderwood** [nickjcroucher/gubbins#49]
I've been trying to run this on Mac OSX and get a seg fault

```
....
subprocess.CalledProcessError: Command 'gubbins -r -v snps_vs_HO.fas.gaps.vcf -t snps_vs_HO.fas.iteration_1 -p snps_vs_HO.fas.gaps.phylip -m 3 snps_vs_HO.fas' returned non-zero exit status -11
```

Any ideas why this may be?

**Comment by aldertzomer** [comment]
Same issue here, Ubuntu 14.04, input is an alignment of the core genome of 61 campylobacter isolates.  No indication what went wrong. I can provide the sequences on request. Gubbins does work on a test genome alignment of 9 isolates. The 61 isolates alignment does contain gap characters (---). Could that be an issue?

**Comment by aldertzomer** [comment]
Issue goes away if I remove all positions with gap characters in the alignment

**Comment by andrewjpage** [comment]
Hi,
Would it be possible for you to send the error message and your alignment to gubbins@sanger.ac.uk and I'll see if I can track down the problem. I've recently pushed out some updates to both gubbins and fastml, so it might be fixed already (hopefully).
Regards,
Andrew
